#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""一次性工具：把当前 SQLite schema 转成 PostgreSQL DDL（含 tenant_id）。

从 PRAGMA 读结构化列信息，不解析 CREATE TABLE 文本——运行时的 DDL 里混着
历史 ALTER TABLE 留下的续行（如 hygiene_employees 的 `, name TEXT ...`）。

外键统一后置为 ALTER TABLE：PG 在 CREATE TABLE 时要求被引用表已存在，
而 SQLite 无此限制（表按字母序创建会踩到）。
"""
import sqlite3
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "data/app.db"
OUT = sys.argv[2] if len(sys.argv) > 2 else "/tmp/pg_schema.sql"

SKIP_PREFIXES = ("sqlite_", "_yoyo_")
SKIP_EXACT = {"yoyo_lock"}

# 本轮不加 tenant_id：租户表本身，以及待重做的认证域
TENANT_EXEMPT = {"admin_user", "sessions", "api_tokens"}

TYPE_MAP = {
    "INTEGER": "BIGINT",
    "INT": "BIGINT",
    "REAL": "DOUBLE PRECISION",
    "FLOAT": "DOUBLE PRECISION",
    "DOUBLE": "DOUBLE PRECISION",
    "TEXT": "TEXT",
    "VARCHAR": "TEXT",
    "BLOB": "BYTEA",
    "NUMERIC": "NUMERIC",
    "BOOLEAN": "BOOLEAN",
    "DATETIME": "TIMESTAMPTZ",
}


def map_type(raw: str) -> str:
    if not raw:
        return "TEXT"
    base = raw.strip().upper().split("(")[0]
    return TYPE_MAP.get(base, "TEXT")


def q(ident: str) -> str:
    return '"' + ident.replace('"', '""') + '"'


def main() -> None:
    conn = sqlite3.connect(SRC)
    conn.row_factory = sqlite3.Row

    tables = [
        r["name"]
        for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
        )
        if not r["name"].startswith(SKIP_PREFIXES) and r["name"] not in SKIP_EXACT
    ]

    lines = [
        "-- PostgreSQL schema generated from the current SQLite schema.",
        "-- Regenerate with scripts/archive/sqlite_to_pg_schema.py (one-off tool).",
        "--",
        "-- 时间戳与金额沿用 SQLite 的存储形态（TEXT ISO 字符串 / DOUBLE PRECISION），",
        "-- 以保持现有查询代码可用；后续可单独迁移为 TIMESTAMPTZ / NUMERIC。",
        "-- 外键后置为 ALTER TABLE，避免 PG 对建表顺序的要求。",
        "",
        "BEGIN;",
        "",
        "DROP TABLE IF EXISTS " + ", ".join(q(t) for t in tables) + " CASCADE;",
        "",
        "CREATE TABLE tenants (",
        "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,",
        "    slug TEXT NOT NULL UNIQUE,",
        "    name TEXT NOT NULL,",
        "    created_at TEXT NOT NULL,",
        "    updated_at TEXT NOT NULL",
        ");",
        "",
        "INSERT INTO tenants (id, slug, name, created_at, updated_at)",
        "VALUES (1, 'main', '默认门店', '', '');",
        "",
        "SELECT setval(pg_get_serial_sequence('tenants', 'id'), 1, true);",
        "",
    ]

    index_statements = []
    fk_statements = []
    composite_uniques = []

    for table in tables:
        cols = list(conn.execute(f"PRAGMA table_info({q(table)})"))
        if not cols:
            continue

        uniques = []
        for idx in conn.execute(f"PRAGMA index_list({q(table)})"):
            if idx["origin"] != "u":
                continue
            idx_cols = [
                r["name"] for r in conn.execute(f"PRAGMA index_info({q(idx['name'])})")
            ]
            uniques.append(idx_cols)

        for fk in conn.execute(f"PRAGMA foreign_key_list({q(table)})"):
            src_col, ref_table, ref_col = fk["from"], fk["table"], fk["to"]
            action = ""
            if fk["on_delete"] and fk["on_delete"] != "NO ACTION":
                action = f" ON DELETE {fk['on_delete']}"
            constraint = "fk_" + table + "_" + src_col
            fk_statements.append(
                f"ALTER TABLE {q(table)} ADD CONSTRAINT {q(constraint)} "
                f"FOREIGN KEY ({q(src_col)}) "
                f"REFERENCES {q(ref_table)}({q(ref_col)}){action};"
            )

        pk_cols = [c["name"] for c in cols if c["pk"]]

        lines.append(f"CREATE TABLE {q(table)} (")
        defs = []

        if table not in TENANT_EXEMPT:
            defs.append(
                "    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id)"
            )

        for c in cols:
            name = c["name"]
            col_type = map_type(c["type"])

            # 单列 INTEGER 主键 -> identity（admin_user 的 CHECK(id=1) 一并去掉，
            # 它是「只允许一个管理员」的硬编码来源）
            if pk_cols == [name] and col_type == "BIGINT":
                defs.append(
                    f'    {q(name)} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
                )
                continue

            parts = [f'    {q(name)} {col_type}']
            # 单列**非整数**主键（sessions.session_id / api_tokens.token_hash /
            # sop_stations.slug / app_settings.key...）也要显式声明，否则 PG 侧
            # 整张表没有主键——行定位、唯一性与 admin 的 rowid 映射都会失效。
            if pk_cols == [name]:
                parts.append("PRIMARY KEY")
            if c["notnull"]:
                parts.append("NOT NULL")
            if c["dflt_value"] is not None:
                parts.append(f"DEFAULT {c['dflt_value']}")
            defs.append(" ".join(parts))

        if pk_cols and len(pk_cols) > 1:
            defs.append(f"    PRIMARY KEY ({', '.join(q(c) for c in pk_cols)})")

        for ucols in uniques:
            if ucols == pk_cols:
                continue
            if table not in TENANT_EXEMPT:
                # 单店时代的唯一约束在多租户下必须收敛到门店内唯一
                ucols = ["tenant_id"] + ucols
                composite_uniques.append(f"{table}({', '.join(ucols)})")
            defs.append(f"    UNIQUE ({', '.join(q(c) for c in ucols)})")

        lines.append(",\n".join(defs))
        lines.append(");")
        lines.append("")

        for idx in conn.execute(f"PRAGMA index_list({q(table)})"):
            if idx["origin"] == "u":
                continue
            idx_cols = [
                r["name"] for r in conn.execute(f"PRAGMA index_info({q(idx['name'])})")
            ]
            if not idx_cols:
                continue
            uniq = "UNIQUE " if idx["unique"] else ""
            idx_name = f"idx_{table}_{'_'.join(idx_cols)}"
            index_statements.append(
                f"CREATE {uniq}INDEX IF NOT EXISTS {q(idx_name)} "
                f"ON {q(table)} ({', '.join(q(c) for c in idx_cols)});"
            )

    lines.append("-- 索引（沿用现有定义，tenant_id 暂不当前导列：单店阶段恒为 1，")
    lines.append("-- 前导无选择性收益；多店数据落库后按实际执行计划再调整）")
    lines.extend(index_statements)
    lines.append("")
    lines.append("-- 外键（后置，规避建表顺序）")
    lines.extend(fk_statements)
    lines.append("")
    lines.append("COMMIT;")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    print(f"表: {len(tables)}  索引: {len(index_statements)}  外键: {len(fk_statements)}")
    print(f"输出: {OUT}")
    print("收敛为复合唯一约束:")
    for u in composite_uniques:
        print("  -", u)


if __name__ == "__main__":
    main()
