#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""仪容仪表的 HTTP 契约：鉴权、两步拍照的上传形状、验收动作与人话报错。

服务层细节在 ``test_hygiene_attire.py``；这里只钉端点行为 —— 尤其是这三条：

- **鉴权**：员工侧要员工会话、管理侧要管理员会话；`_get_attire` 没配好时不能因为
  ``from main import`` 把整个应用拉起来（这里一律 override 掉，跟其它卫生端点的测法一致）。
- **两步拍照**：员工交的那张必须带 ``live=true``（ADR 0050），标准图**不**带也行 ——
  两者在同一个路由模块里，边界要钉住。
- **人话报错**：驳回不写原因、图没交就想验收、还没传标准图，回来的都是中文文案，
  不是内部错误码。
"""

import asyncio
import io
import time
import zipfile
from datetime import datetime
from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from PIL import Image

import api.hygiene as hygiene_module
from config import settings
from database import CHINA_TZ, DatabaseManager
from services.hygiene.archive import HygieneDataArchive
from services.hygiene.attire import HygieneAttire
from services.hygiene.captures import FileCaptureStore
from services.hygiene.images import ImageVariantGenerator
from services.business_day import business_date_of
from services.hygiene.work import HygieneWork
from services.identity.accounts import EmployeeAccounts

# 用**真实当下**：`scope=today` 那条路由由服务端按当下算营业日（06:00 切日），
# 夹具写死一个过去的日期就会跟它差出十几天，导出来是空的。attire 与排班都注入
# 同一个 NOW，所以「今天」在整份夹具里仍是同一个营业日。
NOW = datetime.now(CHINA_TZ)
DAY_PHONE = "13800000001"

ZHANGSAN = 11
LISI = 12

# 排班那条班次的 id：identity 列是 GENERATED BY DEFAULT，可以显式给。
SHIFT_ID = 501

STAFF_VIEW = "/api/hygiene/staff/attire"
STAFF_SUBMIT = "/api/hygiene/staff/attire/submit"
STAFF_STANDARD = "/api/hygiene/staff/attire/standard"
ADMIN_DAY = "/api/hygiene/admin/attire"
ADMIN_STANDARD = "/api/hygiene/admin/attire/standard"
ADMIN_DATA_EXPORT = "/api/hygiene/admin/data/export/jobs"


def _run(coro):
    try:
        loop = asyncio.get_event_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
    return loop.run_until_complete(coro)


def _jpeg(color=(30, 90, 120)) -> bytes:
    output = io.BytesIO()
    Image.new("RGB", (120, 90), color).save(output, format="JPEG", quality=90)
    return output.getvalue()


def _build(tmp_path):
    settings.DATABASE_DIR = str(tmp_path)
    db = DatabaseManager()
    _run(db.connect())
    work = HygieneWork(
        db,
        captures=FileCaptureStore(Path(tmp_path) / "hygiene-captures"),
        now=lambda: NOW,
        image_variants=ImageVariantGenerator(),
    )
    _run(work.prepare())
    attire = HygieneAttire(work, now=lambda: NOW)

    now_iso = NOW.isoformat()
    for employee_id, phone, name in ((ZHANGSAN, DAY_PHONE, "张三"), (LISI, "13800000002", "李四")):
        _run(
            db._conn.execute(
                """INSERT INTO hygiene_employees
                       (id, phone, name, password_hash, permission, approved,
                        created_at, updated_at)
                   VALUES (?, ?, ?, '', '普通员工', 1, ?, ?)""",
                (employee_id, phone, name, now_iso, now_iso),
            )
        )
    # 排班结果行直接铺：attire 的判据就是「那天有没有班次」，它读结果、不读规则。
    #
    # 这里**不走 `SchedulingStore`**：铺规则的入口读的是全局 runtime 里的那个库
    # （`set_runtime` 的实例会被别的用例覆盖），而 HTTP 这一层根本不需要它。
    _run(
        db._conn.execute(
            """INSERT INTO staff_shifts
                   (id, name, sort_order, is_active, created_at, updated_at)
               VALUES (?, '白班', 0, 1, ?, ?)""",
            (SHIFT_ID, now_iso, now_iso),
        )
    )
    _run(
        db._conn.execute(
            """INSERT INTO staff_assignments
                   (employee_id, business_date, shift_id, zone_id, source,
                    created_at, updated_at)
               VALUES (?, ?, ?, NULL, 'manual', ?, ?)""",
            (ZHANGSAN, business_date_of(NOW), SHIFT_ID, now_iso, now_iso),
        )
    )
    # 李四一行都不铺：今天没排到他 —— 员工侧整行不显示，交活也要被拒。
    _run(db._conn.commit())
    return db, work, attire


def _make_app(work, attire, db, *, staff_id=ZHANGSAN, admin=True):
    app = FastAPI()
    app.include_router(hygiene_module.router)
    # `_get_work` / `_get_attire` / `_get_accounts` 都是 `from main import …` 的取值口，
    # 不 override 就会把整个应用（连同 lifespan）拖进测试。
    app.dependency_overrides[hygiene_module._get_work] = lambda: work
    app.dependency_overrides[hygiene_module._get_attire] = lambda: attire
    # 账号走**真实**那一个（没登录时 `get_staff_session(None)` 返回 None → 401）：
    # 「未登录」这条用例要测的就是真鉴权路径，不能把依赖换成一句写死的 401。
    app.dependency_overrides[hygiene_module._get_accounts] = lambda: EmployeeAccounts(db)
    # 归档也是同一个取值口（`from main import hygiene_archive`）：导出那两条路由要用它，
    # 不 override 就是 500 —— 现有 data 那套 HTTP 测试也是这么接的。
    app.dependency_overrides[hygiene_module._get_archive] = lambda: HygieneDataArchive(
        db, work._captures
    )
    if admin:
        app.dependency_overrides[hygiene_module.require_session] = lambda: "test-admin"
    if staff_id is not None:
        app.dependency_overrides[hygiene_module.require_staff_session] = lambda: {
            "session_id": "test-staff",
            "employee": {"id": staff_id, "name": "张三", "phone": DAY_PHONE},
        }
    return app


@pytest.fixture
def attire_http(tmp_path):
    old = settings.DATABASE_DIR
    db, work, attire = _build(tmp_path)
    with TestClient(_make_app(work, attire, db)) as client:
        yield client, attire
    _run(db.close())
    settings.DATABASE_DIR = old


def _set_standard(client, color=(200, 200, 40)):
    return client.post(
        ADMIN_STANDARD,
        files={"file": ("standard.jpg", _jpeg(color), "image/jpeg")},
        data={"markup": "[]"},
    )


# ── 鉴权 ────────────────────────────────────────────────────────────────


def test_staff_endpoints_need_a_staff_session(tmp_path):
    old = settings.DATABASE_DIR
    db, work, attire = _build(tmp_path)
    with TestClient(_make_app(work, attire, db, staff_id=None)) as client:
        assert client.get(STAFF_VIEW).status_code == 401
        assert client.post(
            STAFF_SUBMIT,
            files={"file": ("a.jpg", _jpeg(), "image/jpeg")},
            data={"live": "true"},
        ).status_code == 401
    _run(db.close())
    settings.DATABASE_DIR = old


def test_admin_endpoints_need_an_admin_session(tmp_path):
    old = settings.DATABASE_DIR
    db, work, attire = _build(tmp_path)
    with TestClient(_make_app(work, attire, db, admin=False)) as client:
        assert client.get(ADMIN_DAY).status_code == 401
        assert client.post(
            ADMIN_STANDARD,
            files={"file": ("standard.jpg", _jpeg(), "image/jpeg")},
        ).status_code == 401
        assert client.get(ADMIN_STANDARD).status_code == 401
        assert client.get(f"{ADMIN_DAY}/{ZHANGSAN}/shot").status_code == 401
        assert client.post(f"{ADMIN_DAY}/{ZHANGSAN}/accept").status_code == 401
    _run(db.close())
    settings.DATABASE_DIR = old


# ── 员工侧 ──────────────────────────────────────────────────────────────


def test_staff_view_reports_requirement_and_progress(attire_http):
    client, _attire = attire_http
    body = client.get(STAFF_VIEW).json()["attire"]
    assert body["required"] is True
    assert body["status"] == "todo"
    assert body["has_standard"] is False


def test_submit_requires_live_capture(attire_http):
    client, _attire = attire_http
    assert _set_standard(client).status_code == 200

    # 没有 live 标志 = 从相册挑的：这一条要挡住（ADR 0050）。
    refused = client.post(
        STAFF_SUBMIT,
        files={"file": ("album.jpg", _jpeg(), "image/jpeg")},
        data={"live": "false"},
    )
    assert refused.status_code == 400
    assert "现场" in refused.json()["detail"]

    ok = client.post(
        STAFF_SUBMIT,
        files={"file": ("live.jpg", _jpeg(), "image/jpeg")},
        data={"live": "true"},
    )
    assert ok.status_code == 200
    assert ok.json()["attire"]["status"] == "pending"


def test_submit_before_the_standard_exists_says_so(attire_http):
    client, _attire = attire_http
    refused = client.post(
        STAFF_SUBMIT,
        files={"file": ("live.jpg", _jpeg(), "image/jpeg")},
        data={"live": "true"},
    )
    assert refused.status_code == 400
    assert "标准图" in refused.json()["detail"]


def test_submit_on_a_day_off_is_refused(tmp_path):
    old = settings.DATABASE_DIR
    db, work, attire = _build(tmp_path)
    with TestClient(_make_app(work, attire, db, staff_id=LISI)) as client:
        _set_standard(client)
        refused = client.post(
            STAFF_SUBMIT,
            files={"file": ("live.jpg", _jpeg(), "image/jpeg")},
            data={"live": "true"},
        )
        assert refused.status_code == 400
        assert "没排" in refused.json()["detail"]
        # 李四今天休：员工那一行直接说「不用拍」，前端据此整行不显示。
        assert client.get(STAFF_VIEW).json()["attire"]["required"] is False
    _run(db.close())
    settings.DATABASE_DIR = old


def test_staff_standard_is_404_until_admin_uploads_one(attire_http):
    client, _attire = attire_http
    missing = client.get(STAFF_STANDARD)
    assert missing.status_code == 404
    assert "标准图" in missing.json()["detail"]

    assert _set_standard(client).status_code == 200
    served = client.get(STAFF_STANDARD)
    assert served.status_code == 200
    assert served.headers["content-type"].startswith("image/")


# ── 管理侧 ──────────────────────────────────────────────────────────────


def test_admin_day_and_shot_image(attire_http):
    client, _attire = attire_http
    assert _set_standard(client).status_code == 200

    day = client.get(ADMIN_DAY).json()
    assert [p["employee_id"] for p in day["people"]] == [ZHANGSAN]
    assert day["counts"]["todo"] == 1

    # 还没交：那一格没有图，取图就是 404（不是一张空白图）。
    assert client.get(f"{ADMIN_DAY}/{ZHANGSAN}/shot").status_code == 404

    client.post(
        STAFF_SUBMIT,
        files={"file": ("live.jpg", _jpeg(), "image/jpeg")},
        data={"live": "true"},
    )
    shot = client.get(f"{ADMIN_DAY}/{ZHANGSAN}/shot")
    assert shot.status_code == 200
    assert shot.headers["content-type"].startswith("image/")
    assert client.get(ADMIN_DAY).json()["counts"]["pending"] == 1


def test_reject_requires_a_reason(attire_http):
    client, _attire = attire_http
    _set_standard(client)
    client.post(
        STAFF_SUBMIT,
        files={"file": ("live.jpg", _jpeg(), "image/jpeg")},
        data={"live": "true"},
    )

    blank = client.post(f"{ADMIN_DAY}/{ZHANGSAN}/reject", json={"note": "   "})
    assert blank.status_code == 400
    assert "写明" in blank.json()["detail"]

    ok = client.post(f"{ADMIN_DAY}/{ZHANGSAN}/reject", json={"note": "头发没扎起来"})
    assert ok.status_code == 200
    assert ok.json()["status"] == "rejected"
    # 员工那一侧要能看到原因（他照着这句重拍）。
    assert client.get(STAFF_VIEW).json()["attire"]["note"] == "头发没扎起来"


def test_admin_can_read_the_current_standard(attire_http):
    """管理员那一侧也要能看自己传的是哪一版（跟员工那条分开鉴权）。"""
    client, _attire = attire_http
    missing = client.get(ADMIN_STANDARD)
    assert missing.status_code == 404
    assert "标准图" in missing.json()["detail"]

    _set_standard(client)
    served = client.get(ADMIN_STANDARD)
    assert served.status_code == 200
    assert served.headers["content-type"].startswith("image/")


def test_accept_passes_and_second_accept_is_refused(attire_http):
    client, _attire = attire_http
    _set_standard(client)
    client.post(
        STAFF_SUBMIT,
        files={"file": ("live.jpg", _jpeg(), "image/jpeg")},
        data={"live": "true"},
    )

    first = client.post(f"{ADMIN_DAY}/{ZHANGSAN}/accept")
    assert first.status_code == 200
    assert first.json()["status"] == "passed"

    again = client.post(f"{ADMIN_DAY}/{ZHANGSAN}/accept")
    assert again.status_code == 400
    assert "刷新" in again.json()["detail"]


def test_accept_without_a_shot_is_404(attire_http):
    client, _attire = attire_http
    missing = client.post(f"{ADMIN_DAY}/{ZHANGSAN}/accept")
    assert missing.status_code == 404
    assert "刷新" in missing.json()["detail"]


def test_admin_upload_replaces_the_standard(attire_http):
    client, _attire = attire_http
    first = _set_standard(client).json()["standard"]
    second = _set_standard(client, color=(40, 200, 200)).json()["standard"]
    assert first["capture_id"] != second["capture_id"]
    # 读的是最新那条：员工照着拍的永远是当前这版（页面上那张图跟着换）。
    assert client.get(STAFF_STANDARD).status_code == 200
    assert client.get(ADMIN_DAY).json()["standard_updated_at"] == second["created_at"]


def _wait_export(client, job_id, tries=200):
    """轮询到任务落定（打包是后台任务，今天这点量通常一两轮就好）。"""
    job = {}
    for _ in range(tries):
        job = client.get(f"{ADMIN_DATA_EXPORT}/{job_id}").json()
        if job["state"] != "running":
            return job
        time.sleep(0.05)
    return job


def test_one_click_saves_todays_photos(attire_http):
    """一键保存今天的照片：`scope=today` 由服务端算营业日，包里带仪容仪表那一张。

    「日常卫生照片」那一类由既有的导出用例覆盖（同一个 `iter_records`）；这里钉的是
    新接上的仪容仪表，以及「今天」这个范围口径 —— 前端**不传日期**，就算不出来的
    东西不该让它算。
    """
    client, _attire = attire_http
    assert _set_standard(client).status_code == 200
    assert client.post(
        STAFF_SUBMIT,
        files={"file": ("live.jpg", _jpeg(), "image/jpeg")},
        data={"live": "true"},
    ).status_code == 200

    started = client.post(f"{ADMIN_DATA_EXPORT}?scope=today")
    assert started.status_code == 200
    job = _wait_export(client, started.json()["job_id"])
    assert job["state"] == "done", job
    assert "今天的卫生照片" in (job["filename"] or "")

    packed = client.get(f"{ADMIN_DATA_EXPORT}/{started.json()['job_id']}/download")
    assert packed.status_code == 200
    with zipfile.ZipFile(io.BytesIO(packed.content)) as bundle:
        names = bundle.namelist()
    assert any(name.startswith("照片/仪容仪表/") for name in names), names


def test_unknown_scope_is_refused(attire_http):
    """范围只认「今天」——别的值不猜，回一句人话。"""
    client, _attire = attire_http
    bad = client.post(f"{ADMIN_DATA_EXPORT}?scope=last-week")
    assert bad.status_code == 400
    assert "今天" in bad.json()["detail"]
