#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""PostgreSQL 后端的事务语义与写入路径。

用 PG 的 TEMP 表做验证：会话级、断开即消失，不碰真实业务数据。
CI 环境通常没有 PostgreSQL，整组自动跳过。
"""

import asyncio
import os
import tempfile
import unittest

import aiosqlite

try:  # asyncpg 是 PG 后端依赖；缺失时整组测试跳过（见 pg_available）
    import asyncpg
except ImportError:  # pragma: no cover
    asyncpg = None  # type: ignore[assignment]

from db_core.backend import pg as pg_backend

PROBE_DDL = (
    "CREATE TEMP TABLE probe ("
    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
    "name TEXT NOT NULL, "
    "qty INTEGER NOT NULL DEFAULT 0)"
)


def pg_available() -> bool:
    if asyncpg is None:
        return False

    async def probe() -> bool:
        try:
            conn = await asyncpg.connect(pg_backend.dsn_from_env(), timeout=2)
        except Exception:
            return False
        await conn.close()
        return True

    try:
        return asyncio.run(probe())
    except Exception:
        return False


@unittest.skipUnless(pg_available(), "PostgreSQL 不可用，跳过 PG 后端测试")
class PgTransactionTest(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        self.conn = await pg_backend.connect()
        await self.conn.execute(PROBE_DDL)

    async def asyncTearDown(self):
        await self.conn.close()

    async def test_commit_persists(self):
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("甲",))
        await self.conn.commit()
        cur = await self.conn.execute("SELECT count(*) FROM probe")
        self.assertEqual((await cur.fetchone())[0], 1)

    async def test_rollback_discards_writes(self):
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("乙",))
        self.assertTrue(self.conn.in_transaction())
        await self.conn.rollback()
        self.assertFalse(self.conn.in_transaction())
        cur = await self.conn.execute("SELECT count(*) FROM probe")
        self.assertEqual((await cur.fetchone())[0], 0)

    async def test_writes_are_atomic_across_statements(self):
        """先插后删再回滚，两条语句必须一起撤销（aiosqlite 的 commit 语义）。"""
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("丙",))
        await self.conn.execute("DELETE FROM probe")
        await self.conn.rollback()
        cur = await self.conn.execute("SELECT count(*) FROM probe")
        self.assertEqual((await cur.fetchone())[0], 0)

    async def test_uncommitted_close_rolls_back(self):
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("丁",))
        self.assertTrue(self.conn.in_transaction())
        await self.conn.close()
        # 换一条连接看数据是否真的没落库
        other = await pg_backend.connect()
        try:
            await other.execute(PROBE_DDL)
            cur = await other.execute("SELECT count(*) FROM probe")
            self.assertEqual((await cur.fetchone())[0], 0)
        finally:
            await other.close()


@unittest.skipUnless(pg_available(), "PostgreSQL 不可用，跳过 PG 后端测试")
class PgWritePathTest(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        self.conn = await pg_backend.connect()
        await self.conn.execute(PROBE_DDL)

    async def asyncTearDown(self):
        await self.conn.close()

    async def test_lastrowid_from_returning(self):
        cur = await self.conn.cursor()
        await cur.execute("INSERT INTO probe (name) VALUES (?)", ("甲",))
        first = cur.lastrowid
        self.assertIsNotNone(first)
        await cur.execute("INSERT INTO probe (name) VALUES (?)", ("乙",))
        # 自增主键必须递增，且 lastrowid 要跟着更新
        self.assertEqual(cur.lastrowid, first + 1)

    async def test_insert_or_ignore_conflict_keeps_lastrowid_none(self):
        await self.conn.execute("CREATE TEMP TABLE uniq_probe ("
                                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                                "name TEXT NOT NULL UNIQUE)")
        await self.conn.execute("INSERT OR IGNORE INTO uniq_probe (name) VALUES (?)", ("同",))
        cur = await self.conn.cursor()
        await cur.execute("INSERT OR IGNORE INTO uniq_probe (name) VALUES (?)", ("同",))
        # ON CONFLICT DO NOTHING 命中时没有行被插入，lastrowid 应为 None 而不是报错
        self.assertIsNone(cur.lastrowid)

    async def test_insert_into_table_without_id_column(self):
        """sessions / api_tokens / sop_stations 这类表没有 id 列，不能强加 RETURNING id。"""
        await self.conn.execute("CREATE TEMP TABLE noid ("
                                "code TEXT PRIMARY KEY, val TEXT NOT NULL)")
        cur = await self.conn.cursor()
        await cur.execute("INSERT OR IGNORE INTO noid (code, val) VALUES (?, ?)", ("a", "1"))
        await self.conn.commit()
        rows = await (await self.conn.execute("SELECT val FROM noid WHERE code = ?", ("a",))).fetchall()
        self.assertEqual(len(rows), 1)

    async def test_cte_select_returns_rows(self):
        """CTE（`WITH ... SELECT`）是只读查询，结果集必须照常返回。

        原来只按 `^SELECT` 判定，CTE 被当成 UPDATE/DDL 走 raw.execute：只拿得到
        command tag，结果集丢掉、fetchall() 恒空，而且不报错。卫生端员工端日常清单
        （list_daily_work，全库唯一一处 CTE）因此在 PG 后端下一直返回空——员工端
        一项日常检查都看不到，管理端却正常。
        """
        await self.conn.execute("INSERT INTO probe (name, qty) VALUES (?, ?)", ("乙", 3))
        await self.conn.commit()
        cur = await self.conn.execute(
            "WITH picked AS (SELECT name, qty FROM probe WHERE qty = ?) "
            "SELECT name, qty FROM picked",
            (3,),
        )
        rows = await cur.fetchall()
        self.assertEqual(len(rows), 1)
        self.assertEqual(rows[0]["name"], "乙")

    async def test_update_and_delete_report_rowcount(self):
        await self.conn.execute("INSERT INTO probe (name, qty) VALUES (?, ?)", ("甲", 1))
        await self.conn.execute("INSERT INTO probe (name, qty) VALUES (?, ?)", ("甲", 2))
        await self.conn.commit()
        cur = await self.conn.cursor()
        await cur.execute("UPDATE probe SET qty = ? WHERE name = ?", (9, "甲"))
        self.assertEqual(cur.rowcount, 2)
        await self.conn.commit()
        rows = await (await self.conn.execute("SELECT qty FROM probe ORDER BY id")).fetchall()
        self.assertEqual([r[0] for r in rows], [9, 9])

    async def test_numeric_string_param_is_coerced(self):
        """SQLite 把 '1' 隐式当整数比较，asyncpg 严格拒绝——后端要按需收敛。

        row_to_dict 会把 id 转成字符串（_id = str(id)），所以调用方传
        `WHERE id = ?` 带字符串是仓库里的常态。
        """
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("甲",))
        await self.conn.commit()
        cur = await self.conn.cursor()
        await cur.execute("SELECT name FROM probe WHERE id = ?", ("1",))
        rows = await cur.fetchall()
        self.assertEqual(len(rows), 1)
        self.assertEqual(rows[0][0], "甲")

    async def test_text_column_still_accepts_digit_strings(self):
        """收敛只针对 asyncpg 报错的参数，text 列的数字串不能被误改成 int。"""
        await self.conn.execute(
            "CREATE TEMP TABLE text_probe (code TEXT PRIMARY KEY, val TEXT)"
        )
        await self.conn.execute("INSERT INTO text_probe (code, val) VALUES (?, ?)", ("007", "x"))
        await self.conn.commit()
        rows = await (
            await self.conn.execute("SELECT val FROM text_probe WHERE code = ?", ("007",))
        ).fetchall()
        self.assertEqual(len(rows), 1)


@unittest.skipUnless(pg_available(), "PostgreSQL 不可用，跳过 PG 后端测试")
class PgConcurrencyTest(unittest.IsolatedAsyncioTestCase):
    """同一连接被并发使用时的串行化。

    asyncpg 的单条连接**不允许并发操作**（报 ``InterfaceError: another
    operation is in progress``），而调用方（FastAPI 请求 + 后台调度器）天然
    并发；SQLite 后端由 aiosqlite 内部串行化，所以这个差异只有 PG 会暴露。
    """

    async def asyncSetUp(self):
        self.conn = await pg_backend.connect()
        await self.conn.execute(PROBE_DDL)
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("并发",))
        await self.conn.commit()

    async def asyncTearDown(self):
        await self.conn.close()

    async def test_concurrent_reads_all_succeed(self):
        """并发读同一条连接：不允许出现 InterfaceError。"""

        async def read() -> int:
            cur = await self.conn.execute("SELECT count(*) FROM probe")
            return (await cur.fetchone())[0]

        results = await asyncio.gather(*(read() for _ in range(20)), return_exceptions=True)

        failures = [r for r in results if isinstance(r, BaseException)]
        self.assertEqual(
            failures,
            [],
            f"并发读失败 {len(failures)}/20，首个异常: {type(failures[0]).__name__}: {failures[0]}"
            if failures
            else "",
        )
        self.assertEqual(results, [1] * 20)

    async def test_concurrent_writes_all_land(self):
        """并发写同一条连接：全部写入且行数正确（可重入锁不得丢操作）。"""

        async def write(name: str) -> None:
            await self.conn.execute("INSERT INTO probe (name) VALUES (?)", (name,))
            await self.conn.commit()

        await asyncio.gather(*(write(f"w{i}") for i in range(10)))

        cur = await self.conn.execute("SELECT count(*) FROM probe")
        # 1 条在 setUp 里写入 + 10 条并发写入
        self.assertEqual((await cur.fetchone())[0], 11)

    async def test_failed_statement_releases_connection(self):
        """事务内语句报错 → PG 事务已 aborted，必须立刻回滚。

        否则 aborted 事务会占着串行锁：其他任务全被挡在锁外（全站卡死），
        持有者自己的后续语句也只会收到 InFailedSQLTransactionError。
        """
        with self.assertRaises(asyncpg.exceptions.UniqueViolationError):
            # probe.id 是 IDENTITY，setUp 已占用 id=1
            await self.conn.execute("INSERT INTO probe (id, name) VALUES (?, ?)", (1, "冲突"))

        self.assertFalse(self.conn.in_transaction(), "报错后事务应已被丢弃")

        async def read() -> int:
            cur = await self.conn.execute("SELECT count(*) FROM probe")
            return (await cur.fetchone())[0]

        self.assertEqual(await asyncio.wait_for(read(), timeout=5), 1)

    async def test_stale_transaction_is_cleaned_on_takeover(self):
        """持有事务的任务异常结束后，后续任务不能被那个悬挂事务污染。"""

        async def writer() -> None:
            await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("悬挂",))
            raise RuntimeError("模拟写路径异常退出（未 commit/rollback）")

        with self.assertRaises(RuntimeError):
            await asyncio.create_task(writer())

        # 新任务接管：悬挂事务必须被回滚，未提交的那条不能出现
        cur = await self.conn.execute("SELECT count(*) FROM probe")
        self.assertEqual((await cur.fetchone())[0], 1)
        self.assertFalse(self.conn.in_transaction())

    async def test_open_transaction_blocks_other_tasks_until_commit(self):
        """事务未提交时，其他任务的操作必须在锁上等待，不能落进别人的事务。"""
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("事务中",))
        self.assertTrue(self.conn.in_transaction())

        observed: list[int] = []

        async def competing_read() -> None:
            cur = await self.conn.execute("SELECT count(*) FROM probe")
            observed.append((await cur.fetchone())[0])

        reader = asyncio.create_task(competing_read())
        await asyncio.sleep(0.05)
        # 事务仍在进行：读者应被挡住，看不到未提交数据
        self.assertEqual(observed, [])

        await self.conn.commit()
        await asyncio.wait_for(reader, timeout=5)
        # 提交后读者才拿到锁，看到 setUP 那条 + 事务里那条
        self.assertEqual(observed, [2])


@unittest.skipUnless(pg_available(), "PostgreSQL 不可用，跳过 PG 后端测试")
class PgBackupExportTest(unittest.IsolatedAsyncioTestCase):
    """「导出 DB」（``PgConnection.backup``）在 PG 后端下的端到端验证。

    全程只读：导出走 SELECT，不写业务数据。用最小的 app_settings 而不是 orders
    （十几万行）以免拖慢测试。
    """

    async def asyncSetUp(self):
        self.conn = await pg_backend.connect()
        fd, self._dump_path = tempfile.mkstemp(suffix=".sqlite")
        os.close(fd)

    async def asyncTearDown(self):
        await self.conn.close()
        try:
            os.unlink(self._dump_path)
        except OSError:
            pass

    async def _source_columns(self, table: str) -> list:
        cursor = await self.conn.execute(f"PRAGMA table_info({table})")
        return [row[1] for row in await cursor.fetchall()]

    async def test_backup_exports_schema_and_rows(self):
        target = await aiosqlite.connect(self._dump_path)
        try:
            await self.conn.backup(target, tables=["app_settings"])
        finally:
            await target.close()

        async with aiosqlite.connect(self._dump_path) as dump:
            dump.row_factory = aiosqlite.Row
            cursor = await dump.execute("PRAGMA table_info(app_settings)")
            dumped_columns = [row["name"] for row in await cursor.fetchall()]
            cursor = await dump.execute("SELECT count(*) FROM app_settings")
            dumped_rows = (await cursor.fetchone())[0]

        cursor = await self.conn.execute("SELECT count(*) FROM app_settings")
        source_rows = (await cursor.fetchone())[0]

        self.assertEqual(dumped_columns, await self._source_columns("app_settings"))
        self.assertEqual(dumped_rows, source_rows)

    async def test_backup_skips_tables_absent_from_source(self):
        target = await aiosqlite.connect(self._dump_path)
        try:
            await self.conn.backup(target, tables=["app_settings", "no_such_table"])
        finally:
            await target.close()

        async with aiosqlite.connect(self._dump_path) as dump:
            cursor = await dump.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table'"
            )
            tables = {row[0] for row in await cursor.fetchall()}

        self.assertEqual(tables, {"app_settings"})

    async def test_full_backup_catalogue_has_business_tables_but_no_temp_tables(self):
        """整库导出（tables 省略）的表目录：含业务表，不含会话级 TEMP 表。"""
        await self.conn.execute("CREATE TEMP TABLE backup_probe (id BIGINT)")

        cursor = await self.conn.execute(pg_backend._TABLE_NAMES_SQL)
        names = {row[0] for row in await cursor.fetchall()}

        self.assertIn("orders", names)
        self.assertNotIn("backup_probe", names)


if __name__ == "__main__":
    unittest.main()
