#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""PostgreSQL 后端的事务语义与写入路径。

用 PG 的 TEMP 表做验证：会话级、断开即消失，不碰真实业务数据。
CI 环境通常没有 PostgreSQL，整组自动跳过。
"""

import asyncio
import unittest

from db_core.backend import pg as pg_backend

PROBE_DDL = (
    "CREATE TEMP TABLE probe ("
    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
    "name TEXT NOT NULL, "
    "qty INTEGER NOT NULL DEFAULT 0)"
)


def pg_available() -> bool:
    try:
        import asyncpg  # noqa: F401
    except ImportError:
        return False

    async def probe() -> bool:
        try:
            conn = await asyncpg.connect(pg_backend.dsn_from_env(), timeout=2)
        except Exception:
            return False
        await conn.close()
        return True

    try:
        return asyncio.run(probe())
    except Exception:
        return False


@unittest.skipUnless(pg_available(), "PostgreSQL 不可用，跳过 PG 后端测试")
class PgTransactionTest(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        self.conn = await pg_backend.connect()
        await self.conn.execute(PROBE_DDL)

    async def asyncTearDown(self):
        await self.conn.close()

    async def test_commit_persists(self):
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("甲",))
        await self.conn.commit()
        cur = await self.conn.execute("SELECT count(*) FROM probe")
        self.assertEqual((await cur.fetchone())[0], 1)

    async def test_rollback_discards_writes(self):
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("乙",))
        self.assertTrue(self.conn.in_transaction())
        await self.conn.rollback()
        self.assertFalse(self.conn.in_transaction())
        cur = await self.conn.execute("SELECT count(*) FROM probe")
        self.assertEqual((await cur.fetchone())[0], 0)

    async def test_writes_are_atomic_across_statements(self):
        """先插后删再回滚，两条语句必须一起撤销（aiosqlite 的 commit 语义）。"""
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("丙",))
        await self.conn.execute("DELETE FROM probe")
        await self.conn.rollback()
        cur = await self.conn.execute("SELECT count(*) FROM probe")
        self.assertEqual((await cur.fetchone())[0], 0)

    async def test_uncommitted_close_rolls_back(self):
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("丁",))
        self.assertTrue(self.conn.in_transaction())
        await self.conn.close()
        # 换一条连接看数据是否真的没落库
        other = await pg_backend.connect()
        try:
            await other.execute(PROBE_DDL)
            cur = await other.execute("SELECT count(*) FROM probe")
            self.assertEqual((await cur.fetchone())[0], 0)
        finally:
            await other.close()


@unittest.skipUnless(pg_available(), "PostgreSQL 不可用，跳过 PG 后端测试")
class PgWritePathTest(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        self.conn = await pg_backend.connect()
        await self.conn.execute(PROBE_DDL)

    async def asyncTearDown(self):
        await self.conn.close()

    async def test_lastrowid_from_returning(self):
        cur = await self.conn.cursor()
        await cur.execute("INSERT INTO probe (name) VALUES (?)", ("甲",))
        first = cur.lastrowid
        self.assertIsNotNone(first)
        await cur.execute("INSERT INTO probe (name) VALUES (?)", ("乙",))
        # 自增主键必须递增，且 lastrowid 要跟着更新
        self.assertEqual(cur.lastrowid, first + 1)

    async def test_insert_or_ignore_conflict_keeps_lastrowid_none(self):
        await self.conn.execute("CREATE TEMP TABLE uniq_probe ("
                                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                                "name TEXT NOT NULL UNIQUE)")
        await self.conn.execute("INSERT OR IGNORE INTO uniq_probe (name) VALUES (?)", ("同",))
        cur = await self.conn.cursor()
        await cur.execute("INSERT OR IGNORE INTO uniq_probe (name) VALUES (?)", ("同",))
        # ON CONFLICT DO NOTHING 命中时没有行被插入，lastrowid 应为 None 而不是报错
        self.assertIsNone(cur.lastrowid)

    async def test_insert_into_table_without_id_column(self):
        """sessions / api_tokens / sop_stations 这类表没有 id 列，不能强加 RETURNING id。"""
        await self.conn.execute("CREATE TEMP TABLE noid ("
                                "code TEXT PRIMARY KEY, val TEXT NOT NULL)")
        cur = await self.conn.cursor()
        await cur.execute("INSERT OR IGNORE INTO noid (code, val) VALUES (?, ?)", ("a", "1"))
        await self.conn.commit()
        rows = await (await self.conn.execute("SELECT val FROM noid WHERE code = ?", ("a",))).fetchall()
        self.assertEqual(len(rows), 1)

    async def test_update_and_delete_report_rowcount(self):
        await self.conn.execute("INSERT INTO probe (name, qty) VALUES (?, ?)", ("甲", 1))
        await self.conn.execute("INSERT INTO probe (name, qty) VALUES (?, ?)", ("甲", 2))
        await self.conn.commit()
        cur = await self.conn.cursor()
        await cur.execute("UPDATE probe SET qty = ? WHERE name = ?", (9, "甲"))
        self.assertEqual(cur.rowcount, 2)
        await self.conn.commit()
        rows = await (await self.conn.execute("SELECT qty FROM probe ORDER BY id")).fetchall()
        self.assertEqual([r[0] for r in rows], [9, 9])

    async def test_numeric_string_param_is_coerced(self):
        """SQLite 把 '1' 隐式当整数比较，asyncpg 严格拒绝——后端要按需收敛。

        row_to_dict 会把 id 转成字符串（_id = str(id)），所以调用方传
        `WHERE id = ?` 带字符串是仓库里的常态。
        """
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("甲",))
        await self.conn.commit()
        cur = await self.conn.cursor()
        await cur.execute("SELECT name FROM probe WHERE id = ?", ("1",))
        rows = await cur.fetchall()
        self.assertEqual(len(rows), 1)
        self.assertEqual(rows[0][0], "甲")

    async def test_text_column_still_accepts_digit_strings(self):
        """收敛只针对 asyncpg 报错的参数，text 列的数字串不能被误改成 int。"""
        await self.conn.execute(
            "CREATE TEMP TABLE text_probe (code TEXT PRIMARY KEY, val TEXT)"
        )
        await self.conn.execute("INSERT INTO text_probe (code, val) VALUES (?, ?)", ("007", "x"))
        await self.conn.commit()
        rows = await (
            await self.conn.execute("SELECT val FROM text_probe WHERE code = ?", ("007",))
        ).fetchall()
        self.assertEqual(len(rows), 1)


@unittest.skipUnless(pg_available(), "PostgreSQL 不可用，跳过 PG 后端测试")
class PgConcurrencyTest(unittest.IsolatedAsyncioTestCase):
    """同一连接被并发使用时的串行化。

    asyncpg 的单条连接**不允许并发操作**（报 ``InterfaceError: another
    operation is in progress``），而调用方（FastAPI 请求 + 后台调度器）天然
    并发；SQLite 后端由 aiosqlite 内部串行化，所以这个差异只有 PG 会暴露。
    """

    async def asyncSetUp(self):
        self.conn = await pg_backend.connect()
        await self.conn.execute(PROBE_DDL)
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("并发",))
        await self.conn.commit()

    async def asyncTearDown(self):
        await self.conn.close()

    async def test_concurrent_reads_all_succeed(self):
        """并发读同一条连接：不允许出现 InterfaceError。"""

        async def read() -> int:
            cur = await self.conn.execute("SELECT count(*) FROM probe")
            return (await cur.fetchone())[0]

        results = await asyncio.gather(*(read() for _ in range(20)), return_exceptions=True)

        failures = [r for r in results if isinstance(r, BaseException)]
        self.assertEqual(
            failures,
            [],
            f"并发读失败 {len(failures)}/20，首个异常: {type(failures[0]).__name__}: {failures[0]}"
            if failures
            else "",
        )
        self.assertEqual(results, [1] * 20)

    async def test_concurrent_writes_all_land(self):
        """并发写同一条连接：全部写入且行数正确（可重入锁不得丢操作）。"""

        async def write(name: str) -> None:
            await self.conn.execute("INSERT INTO probe (name) VALUES (?)", (name,))
            await self.conn.commit()

        await asyncio.gather(*(write(f"w{i}") for i in range(10)))

        cur = await self.conn.execute("SELECT count(*) FROM probe")
        # 1 条在 setUp 里写入 + 10 条并发写入
        self.assertEqual((await cur.fetchone())[0], 11)

    async def test_open_transaction_blocks_other_tasks_until_commit(self):
        """事务未提交时，其他任务的操作必须在锁上等待，不能落进别人的事务。"""
        await self.conn.execute("INSERT INTO probe (name) VALUES (?)", ("事务中",))
        self.assertTrue(self.conn.in_transaction())

        observed: list[int] = []

        async def competing_read() -> None:
            cur = await self.conn.execute("SELECT count(*) FROM probe")
            observed.append((await cur.fetchone())[0])

        reader = asyncio.create_task(competing_read())
        await asyncio.sleep(0.05)
        # 事务仍在进行：读者应被挡住，看不到未提交数据
        self.assertEqual(observed, [])

        await self.conn.commit()
        await asyncio.wait_for(reader, timeout=5)
        # 提交后读者才拿到锁，看到 setUP 那条 + 事务里那条
        self.assertEqual(observed, [2])


if __name__ == "__main__":
    unittest.main()
