-- PostgreSQL schema generated from the current SQLite schema.
-- Regenerate with scripts/archive/sqlite_to_pg_schema.py (one-off tool).
--
-- 时间戳与金额沿用 SQLite 的存储形态（TEXT ISO 字符串 / DOUBLE PRECISION），
-- 以保持现有查询代码可用；后续可单独迁移为 TIMESTAMPTZ / NUMERIC。
-- 外键后置为 ALTER TABLE，避免 PG 对建表顺序的要求。

BEGIN;

DROP TABLE IF EXISTS "admin_user", "api_tokens", "app_settings", "dish_stations", "hygiene_board_events", "hygiene_capture_variants", "hygiene_daily_instances", "hygiene_daily_items", "hygiene_daily_submissions", "hygiene_deep_clean_instances", "hygiene_deep_clean_items", "hygiene_deep_clean_overdue_notices", "hygiene_deep_clean_submissions", "hygiene_employees", "hygiene_fix_overdue_notices", "hygiene_fix_reshoots", "hygiene_fix_tickets", "hygiene_overdue_notices", "hygiene_settings", "hygiene_shift_picks", "hygiene_staff_sessions", "hygiene_standards", "hygiene_teaching_examples", "hygiene_zones", "orders", "prep_batches", "prep_items", "prep_plan_item_slots", "prep_plan_items", "prep_plan_runs", "prep_stock_movements", "report_dishes", "semi_finished_rules", "sessions", "sop_recipes", "sop_recipes_history", "sop_stations", "stations", "tables", "wecom_push_jobs", "wecom_push_logs", "wecom_push_webhooks" CASCADE;

CREATE TABLE tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

INSERT INTO tenants (id, slug, name, created_at, updated_at)
VALUES (1, 'main', '默认门店', '', '');

SELECT setval(pg_get_serial_sequence('tenants', 'id'), 1, true);

CREATE TABLE "admin_user" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    UNIQUE ("username")
);

CREATE TABLE "api_tokens" (
    "token_hash" TEXT,
    "label" TEXT DEFAULT '',
    "expires_at" TEXT,
    "created_at" TEXT NOT NULL,
    "revoked_at" TEXT
);

CREATE TABLE "app_settings" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "key" TEXT,
    "value" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

CREATE TABLE "dish_stations" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dish_name" TEXT NOT NULL,
    "station_id" TEXT NOT NULL,
    "notes" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "dish_name")
);

CREATE TABLE "hygiene_board_events" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "board" TEXT NOT NULL,
    "event_type" TEXT NOT NULL,
    "zone_id" BIGINT,
    "employee_id" BIGINT,
    "item_id" BIGINT,
    "shift" TEXT,
    "business_date" TEXT,
    "occurred_at" TEXT NOT NULL
);

CREATE TABLE "hygiene_capture_variants" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "source_capture_id" TEXT NOT NULL,
    "variant" TEXT NOT NULL,
    "capture_id" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "width" BIGINT NOT NULL,
    "height" BIGINT NOT NULL,
    "byte_size" BIGINT NOT NULL,
    "content_sha256" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("source_capture_id", "variant")
);

CREATE TABLE "hygiene_daily_instances" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "business_date" TEXT NOT NULL,
    "shift" TEXT NOT NULL,
    "item_id" BIGINT NOT NULL,
    "status" TEXT NOT NULL,
    "pending_submission_id" BIGINT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "business_date", "shift", "item_id")
);

CREATE TABLE "hygiene_daily_items" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "zone_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "current_standard_id" BIGINT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "zone_id", "name")
);

CREATE TABLE "hygiene_daily_submissions" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "instance_id" BIGINT NOT NULL,
    "capture_id" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "frozen_standard_id" BIGINT NOT NULL,
    "submitter_id" BIGINT NOT NULL,
    "submitter_phone" TEXT NOT NULL,
    "zone_name" TEXT NOT NULL,
    "captured_at" TEXT NOT NULL,
    "created_at" TEXT NOT NULL
);

CREATE TABLE "hygiene_deep_clean_instances" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "business_date" TEXT NOT NULL,
    "item_id" BIGINT NOT NULL,
    "status" TEXT NOT NULL,
    "pending_submission_id" BIGINT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "business_date", "item_id")
);

CREATE TABLE "hygiene_deep_clean_items" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "weekday" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "weekday", "name")
);

CREATE TABLE "hygiene_deep_clean_overdue_notices" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "business_date" TEXT NOT NULL,
    "notified_at" TEXT NOT NULL
);

CREATE TABLE "hygiene_deep_clean_submissions" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "instance_id" BIGINT NOT NULL,
    "before_capture_id" TEXT NOT NULL,
    "after_capture_id" TEXT NOT NULL,
    "before_content_type" TEXT NOT NULL,
    "after_content_type" TEXT NOT NULL,
    "submitter_id" BIGINT NOT NULL,
    "submitter_phone" TEXT NOT NULL,
    "item_name" TEXT NOT NULL,
    "before_captured_at" TEXT NOT NULL,
    "after_captured_at" TEXT NOT NULL,
    "created_at" TEXT NOT NULL
);

CREATE TABLE "hygiene_employees" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "phone" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "job_title" TEXT NOT NULL DEFAULT '',
    "permission" TEXT NOT NULL DEFAULT '普通员工',
    "approved" BIGINT NOT NULL DEFAULT 0,
    "disabled" BIGINT NOT NULL DEFAULT 0,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "name" TEXT NOT NULL DEFAULT '',
    UNIQUE ("tenant_id", "phone")
);

CREATE TABLE "hygiene_fix_overdue_notices" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "ticket_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "notified_at" TEXT NOT NULL
);

CREATE TABLE "hygiene_fix_reshoots" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ticket_id" BIGINT NOT NULL,
    "capture_id" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "photographer_id" BIGINT NOT NULL,
    "photographer_phone" TEXT NOT NULL,
    "zone_name" TEXT NOT NULL,
    "captured_at" TEXT NOT NULL,
    "created_at" TEXT NOT NULL
);

CREATE TABLE "hygiene_fix_tickets" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "zone_id" BIGINT NOT NULL,
    "ticket_type" TEXT NOT NULL,
    "body_text" TEXT NOT NULL,
    "duration_seconds" BIGINT NOT NULL,
    "deadline" TEXT NOT NULL,
    "opener_kind" TEXT NOT NULL,
    "opener_id" BIGINT,
    "opener_phone" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "capture_id" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "markup_json" TEXT NOT NULL DEFAULT '[]',
    "pending_reshoot_id" BIGINT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

CREATE TABLE "hygiene_overdue_notices" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "business_date" TEXT NOT NULL,
    "shift" TEXT NOT NULL,
    "item_id" BIGINT NOT NULL,
    "zone_id" BIGINT NOT NULL,
    "notified_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "business_date", "shift", "item_id")
);

CREATE TABLE "hygiene_settings" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

CREATE TABLE "hygiene_shift_picks" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employee_id" BIGINT NOT NULL,
    "business_date" TEXT NOT NULL,
    "shift" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "zone_id" BIGINT,
    UNIQUE ("tenant_id", "employee_id", "business_date")
);

CREATE TABLE "hygiene_staff_sessions" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "session_id" TEXT NOT NULL,
    "employee_id" BIGINT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "last_seen_at" TEXT NOT NULL
);

CREATE TABLE "hygiene_standards" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "item_id" BIGINT NOT NULL,
    "capture_id" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "markup_json" TEXT NOT NULL DEFAULT '[]',
    "created_at" TEXT NOT NULL,
    "byte_size" BIGINT,
    "content_sha256" TEXT
);

CREATE TABLE "hygiene_teaching_examples" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "kind" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "left_label" TEXT NOT NULL,
    "right_label" TEXT NOT NULL,
    "left_capture_id" TEXT NOT NULL,
    "right_capture_id" TEXT NOT NULL,
    "left_content_type" TEXT NOT NULL,
    "right_content_type" TEXT NOT NULL,
    "left_markup_json" TEXT NOT NULL DEFAULT '[]',
    "item_id" BIGINT,
    "shift" TEXT,
    "created_at" TEXT NOT NULL
);

CREATE TABLE "hygiene_zones" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "day_shift" BIGINT NOT NULL DEFAULT 1,
    "night_shift" BIGINT NOT NULL DEFAULT 1,
    UNIQUE ("tenant_id", "name")
);

CREATE TABLE "orders" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "business_flow_id" TEXT,
    "table_number" TEXT NOT NULL,
    "dish_name" TEXT NOT NULL,
    "quantity" BIGINT NOT NULL,
    "order_time" TEXT NOT NULL,
    "price" DOUBLE PRECISION DEFAULT 0.0,
    "total_amount" DOUBLE PRECISION DEFAULT 0.0,
    "status" TEXT DEFAULT '未结',
    "category" TEXT DEFAULT '',
    "station" TEXT DEFAULT '',
    "priority" TEXT DEFAULT 'normal',
    "notes" TEXT,
    "dish_status" TEXT DEFAULT '待出餐',
    "ready_time" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "source" TEXT DEFAULT '',
    "steamer_id" TEXT,
    "port_index" BIGINT,
    "stack_order" BIGINT,
    "loaded_at" TEXT,
    "is_hold" BIGINT DEFAULT 0,
    "is_rushed" BIGINT DEFAULT 0,
    "fired_at" TEXT
);

CREATE TABLE "prep_batches" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "prep_item_id" BIGINT,
    "item_name" TEXT NOT NULL,
    "produced_qty" DOUBLE PRECISION NOT NULL,
    "remaining_qty" DOUBLE PRECISION NOT NULL,
    "unit" TEXT NOT NULL DEFAULT '',
    "produced_at" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "operator" TEXT NOT NULL DEFAULT '',
    "notes" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

CREATE TABLE "prep_items" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "item_name" TEXT NOT NULL,
    "station" TEXT NOT NULL DEFAULT '',
    "position" TEXT NOT NULL DEFAULT '',
    "category" TEXT NOT NULL DEFAULT '',
    "unit" TEXT NOT NULL DEFAULT '',
    "shelf_life_hours" DOUBLE PRECISION NOT NULL DEFAULT 24,
    "lead_time_hours" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "min_batch_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "safety_stock_ratio" DOUBLE PRECISION NOT NULL DEFAULT 0.15,
    "active" BIGINT NOT NULL DEFAULT 1,
    "notes" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "item_name", "unit")
);

CREATE TABLE "prep_plan_item_slots" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "run_id" BIGINT NOT NULL,
    "plan_item_id" BIGINT NOT NULL,
    "prep_item_id" BIGINT,
    "item_name" TEXT NOT NULL,
    "unit" TEXT NOT NULL DEFAULT '',
    "slot_start" TEXT NOT NULL,
    "slot_end" TEXT NOT NULL,
    "forecast_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "available_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "recommended_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "created_at" TEXT NOT NULL
);

CREATE TABLE "prep_plan_items" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "run_id" BIGINT NOT NULL,
    "prep_item_id" BIGINT,
    "item_name" TEXT NOT NULL,
    "station" TEXT NOT NULL DEFAULT '',
    "position" TEXT NOT NULL DEFAULT '',
    "unit" TEXT NOT NULL DEFAULT '',
    "forecast_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "safety_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "available_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "recommended_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "risk_level" TEXT NOT NULL DEFAULT 'normal',
    "confidence" TEXT NOT NULL DEFAULT 'none',
    "reason" TEXT NOT NULL DEFAULT '',
    "created_at" TEXT NOT NULL
);

CREATE TABLE "prep_plan_runs" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "plan_date" TEXT NOT NULL,
    "target_start" TEXT NOT NULL,
    "target_end" TEXT NOT NULL,
    "method" TEXT NOT NULL DEFAULT 'weighted_history',
    "created_by" TEXT NOT NULL DEFAULT '',
    "item_count" BIGINT NOT NULL DEFAULT 0,
    "missing_rule_count" BIGINT NOT NULL DEFAULT 0,
    "high_risk_count" BIGINT NOT NULL DEFAULT 0,
    "expiry_risk_count" BIGINT NOT NULL DEFAULT 0,
    "waste_risk_count" BIGINT NOT NULL DEFAULT 0,
    "summary_json" TEXT,
    "created_at" TEXT NOT NULL
);

CREATE TABLE "prep_stock_movements" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "batch_id" BIGINT,
    "prep_item_id" BIGINT,
    "item_name" TEXT NOT NULL,
    "unit" TEXT NOT NULL DEFAULT '',
    "movement_type" TEXT NOT NULL,
    "qty_delta" DOUBLE PRECISION NOT NULL,
    "reason" TEXT NOT NULL DEFAULT '',
    "operator" TEXT NOT NULL DEFAULT '',
    "source_type" TEXT NOT NULL DEFAULT '',
    "source_id" TEXT NOT NULL DEFAULT '',
    "created_at" TEXT NOT NULL
);

CREATE TABLE "report_dishes" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dish_name" TEXT NOT NULL,
    "display_order" BIGINT NOT NULL DEFAULT 0,
    "notes" TEXT,
    "created_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "dish_name")
);

CREATE TABLE "semi_finished_rules" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dish_name" TEXT NOT NULL,
    "semi_name" TEXT NOT NULL,
    "position" TEXT NOT NULL DEFAULT '',
    "factor" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "unit" TEXT NOT NULL DEFAULT '',
    "category" TEXT NOT NULL DEFAULT '',
    "notes" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

CREATE TABLE "sessions" (
    "session_id" TEXT,
    "expires_at" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "last_seen_at" TEXT NOT NULL
);

CREATE TABLE "sop_recipes" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "station_slug" TEXT NOT NULL,
    "section" TEXT NOT NULL,
    "recipe_name" TEXT NOT NULL,
    "body_markdown" TEXT NOT NULL,
    "sort_order" BIGINT NOT NULL,
    "is_new" BIGINT NOT NULL DEFAULT 0,
    "is_active" BIGINT NOT NULL DEFAULT 1,
    "updated_at" TEXT NOT NULL,
    "ingredients_json" TEXT,
    "steps_json" TEXT,
    "tips_json" TEXT,
    "base_servings_qty" DOUBLE PRECISION,
    "base_servings_unit" TEXT,
    "legacy_markdown" TEXT,
    "needs_review" BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE "sop_recipes_history" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "recipe_id" BIGINT NOT NULL,
    "station_slug" TEXT NOT NULL,
    "section" TEXT NOT NULL,
    "recipe_name" TEXT NOT NULL,
    "body_markdown" TEXT NOT NULL,
    "sort_order" BIGINT NOT NULL,
    "is_new" BIGINT NOT NULL DEFAULT 0,
    "changed_at" TEXT NOT NULL,
    "ingredients_json" TEXT,
    "steps_json" TEXT,
    "tips_json" TEXT,
    "base_servings_qty" DOUBLE PRECISION,
    "base_servings_unit" TEXT
);

CREATE TABLE "sop_stations" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

CREATE TABLE "stations" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "station_id" TEXT NOT NULL,
    "name" TEXT,
    "color" TEXT,
    "config" TEXT,
    UNIQUE ("tenant_id", "station_id")
);

CREATE TABLE "tables" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "table_number" TEXT NOT NULL,
    "amount" DOUBLE PRECISION DEFAULT 0.0,
    "people" BIGINT DEFAULT 0,
    "duration" BIGINT DEFAULT 0,
    "status" TEXT DEFAULT 'empty',
    "updated_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "table_number")
);

CREATE TABLE "wecom_push_jobs" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "webhook_id" BIGINT NOT NULL,
    "push_type" TEXT NOT NULL DEFAULT 'sales_report_text',
    "schedule_time" TEXT NOT NULL,
    "date_range_mode" TEXT NOT NULL DEFAULT 'today',
    "station" TEXT NOT NULL DEFAULT '',
    "enabled" BIGINT NOT NULL DEFAULT 1,
    "last_sent_date" TEXT NOT NULL DEFAULT '',
    "notes" TEXT NOT NULL DEFAULT '',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

CREATE TABLE "wecom_push_logs" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "job_id" BIGINT,
    "webhook_id" BIGINT,
    "webhook_name" TEXT NOT NULL DEFAULT '',
    "push_type" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL,
    "message_bytes" BIGINT NOT NULL DEFAULT 0,
    "error" TEXT NOT NULL DEFAULT '',
    "response_text" TEXT NOT NULL DEFAULT '',
    "sent_at" TEXT NOT NULL
);

CREATE TABLE "wecom_push_webhooks" (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "webhook_url_encrypted" TEXT NOT NULL,
    "webhook_url_masked" TEXT NOT NULL DEFAULT '',
    "enabled" BIGINT NOT NULL DEFAULT 1,
    "notes" TEXT NOT NULL DEFAULT '',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

-- 索引（沿用现有定义，tenant_id 暂不当前导列：单店阶段恒为 1，
-- 前导无选择性收益；多店数据落库后按实际执行计划再调整）
CREATE UNIQUE INDEX IF NOT EXISTS "idx_api_tokens_token_hash" ON "api_tokens" ("token_hash");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_app_settings_key" ON "app_settings" ("key");
CREATE INDEX IF NOT EXISTS "idx_hygiene_board_events_board_occurred_at_id" ON "hygiene_board_events" ("board", "occurred_at", "id");
CREATE INDEX IF NOT EXISTS "idx_hygiene_board_events_board_occurred_at" ON "hygiene_board_events" ("board", "occurred_at");
CREATE INDEX IF NOT EXISTS "idx_hygiene_capture_variants_created_at" ON "hygiene_capture_variants" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_hygiene_capture_variants_capture_id" ON "hygiene_capture_variants" ("capture_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_hygiene_capture_variants_source_capture_id_variant" ON "hygiene_capture_variants" ("source_capture_id", "variant");
CREATE INDEX IF NOT EXISTS "idx_hygiene_daily_instances_business_date_shift" ON "hygiene_daily_instances" ("business_date", "shift");
CREATE INDEX IF NOT EXISTS "idx_hygiene_daily_items_zone_id" ON "hygiene_daily_items" ("zone_id");
CREATE INDEX IF NOT EXISTS "idx_hygiene_daily_submissions_instance_id" ON "hygiene_daily_submissions" ("instance_id");
CREATE INDEX IF NOT EXISTS "idx_hygiene_deep_clean_instances_business_date" ON "hygiene_deep_clean_instances" ("business_date");
CREATE INDEX IF NOT EXISTS "idx_hygiene_deep_clean_items_weekday" ON "hygiene_deep_clean_items" ("weekday");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_hygiene_deep_clean_overdue_notices_business_date" ON "hygiene_deep_clean_overdue_notices" ("business_date");
CREATE INDEX IF NOT EXISTS "idx_hygiene_deep_clean_submissions_instance_id" ON "hygiene_deep_clean_submissions" ("instance_id");
CREATE INDEX IF NOT EXISTS "idx_hygiene_employees_phone" ON "hygiene_employees" ("phone");
CREATE INDEX IF NOT EXISTS "idx_hygiene_fix_reshoots_ticket_id" ON "hygiene_fix_reshoots" ("ticket_id");
CREATE INDEX IF NOT EXISTS "idx_hygiene_fix_tickets_status_deadline" ON "hygiene_fix_tickets" ("status", "deadline");
CREATE INDEX IF NOT EXISTS "idx_hygiene_overdue_notices_business_date_shift" ON "hygiene_overdue_notices" ("business_date", "shift");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_hygiene_settings_key" ON "hygiene_settings" ("key");
CREATE INDEX IF NOT EXISTS "idx_hygiene_shift_picks_business_date" ON "hygiene_shift_picks" ("business_date");
CREATE INDEX IF NOT EXISTS "idx_hygiene_staff_sessions_employee_id" ON "hygiene_staff_sessions" ("employee_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_hygiene_staff_sessions_session_id" ON "hygiene_staff_sessions" ("session_id");
CREATE INDEX IF NOT EXISTS "idx_hygiene_standards_item_id" ON "hygiene_standards" ("item_id");
CREATE INDEX IF NOT EXISTS "idx_hygiene_teaching_examples_created_at" ON "hygiene_teaching_examples" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_hygiene_zones_name" ON "hygiene_zones" ("name");
CREATE INDEX IF NOT EXISTS "idx_orders_source" ON "orders" ("source");
CREATE INDEX IF NOT EXISTS "idx_orders_station_order_time" ON "orders" ("station", "order_time");
CREATE INDEX IF NOT EXISTS "idx_orders_order_time_station" ON "orders" ("order_time", "station");
CREATE INDEX IF NOT EXISTS "idx_orders_business_flow_id" ON "orders" ("business_flow_id");
CREATE INDEX IF NOT EXISTS "idx_orders_dish_name" ON "orders" ("dish_name");
CREATE INDEX IF NOT EXISTS "idx_orders_order_time" ON "orders" ("order_time");
CREATE INDEX IF NOT EXISTS "idx_orders_table_number" ON "orders" ("table_number");
CREATE INDEX IF NOT EXISTS "idx_orders_station" ON "orders" ("station");
CREATE INDEX IF NOT EXISTS "idx_prep_batches_item_name_unit" ON "prep_batches" ("item_name", "unit");
CREATE INDEX IF NOT EXISTS "idx_prep_batches_expires_at" ON "prep_batches" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_prep_batches_item_name_status" ON "prep_batches" ("item_name", "status");
CREATE INDEX IF NOT EXISTS "idx_prep_items_station" ON "prep_items" ("station");
CREATE INDEX IF NOT EXISTS "idx_prep_items_item_name" ON "prep_items" ("item_name");
CREATE INDEX IF NOT EXISTS "idx_prep_items_active" ON "prep_items" ("active");
CREATE INDEX IF NOT EXISTS "idx_prep_plan_item_slots_item_name_slot_start" ON "prep_plan_item_slots" ("item_name", "slot_start");
CREATE INDEX IF NOT EXISTS "idx_prep_plan_item_slots_run_id" ON "prep_plan_item_slots" ("run_id");
CREATE INDEX IF NOT EXISTS "idx_prep_plan_items_item_name_unit" ON "prep_plan_items" ("item_name", "unit");
CREATE INDEX IF NOT EXISTS "idx_prep_plan_items_run_id" ON "prep_plan_items" ("run_id");
CREATE INDEX IF NOT EXISTS "idx_prep_plan_runs_created_at" ON "prep_plan_runs" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_prep_plan_runs_plan_date" ON "prep_plan_runs" ("plan_date");
CREATE INDEX IF NOT EXISTS "idx_prep_stock_movements_item_name_created_at" ON "prep_stock_movements" ("item_name", "created_at");
CREATE INDEX IF NOT EXISTS "idx_prep_stock_movements_batch_id" ON "prep_stock_movements" ("batch_id");
CREATE INDEX IF NOT EXISTS "idx_report_dishes_display_order" ON "report_dishes" ("display_order");
CREATE INDEX IF NOT EXISTS "idx_semi_finished_rules_dish_name" ON "semi_finished_rules" ("dish_name");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_sessions_session_id" ON "sessions" ("session_id");
CREATE INDEX IF NOT EXISTS "idx_sop_recipes_station_slug_sort_order" ON "sop_recipes" ("station_slug", "sort_order");
CREATE INDEX IF NOT EXISTS "idx_sop_recipes_history_recipe_id_changed_at" ON "sop_recipes_history" ("recipe_id", "changed_at");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_sop_stations_slug" ON "sop_stations" ("slug");
CREATE INDEX IF NOT EXISTS "idx_wecom_push_jobs_webhook_id" ON "wecom_push_jobs" ("webhook_id");
CREATE INDEX IF NOT EXISTS "idx_wecom_push_jobs_enabled_schedule_time" ON "wecom_push_jobs" ("enabled", "schedule_time");
CREATE INDEX IF NOT EXISTS "idx_wecom_push_logs_job_id" ON "wecom_push_logs" ("job_id");
CREATE INDEX IF NOT EXISTS "idx_wecom_push_logs_sent_at" ON "wecom_push_logs" ("sent_at");
CREATE INDEX IF NOT EXISTS "idx_wecom_push_webhooks_enabled" ON "wecom_push_webhooks" ("enabled");

-- 外键（后置，规避建表顺序）
ALTER TABLE "hygiene_daily_instances" ADD CONSTRAINT "fk_hygiene_daily_instances_item_id" FOREIGN KEY ("item_id") REFERENCES "hygiene_daily_items"("id");
ALTER TABLE "hygiene_daily_items" ADD CONSTRAINT "fk_hygiene_daily_items_zone_id" FOREIGN KEY ("zone_id") REFERENCES "hygiene_zones"("id");
ALTER TABLE "hygiene_daily_submissions" ADD CONSTRAINT "fk_hygiene_daily_submissions_frozen_standard_id" FOREIGN KEY ("frozen_standard_id") REFERENCES "hygiene_standards"("id");
ALTER TABLE "hygiene_daily_submissions" ADD CONSTRAINT "fk_hygiene_daily_submissions_instance_id" FOREIGN KEY ("instance_id") REFERENCES "hygiene_daily_instances"("id");
ALTER TABLE "hygiene_deep_clean_instances" ADD CONSTRAINT "fk_hygiene_deep_clean_instances_item_id" FOREIGN KEY ("item_id") REFERENCES "hygiene_deep_clean_items"("id");
ALTER TABLE "hygiene_deep_clean_submissions" ADD CONSTRAINT "fk_hygiene_deep_clean_submissions_instance_id" FOREIGN KEY ("instance_id") REFERENCES "hygiene_deep_clean_instances"("id");
ALTER TABLE "hygiene_fix_overdue_notices" ADD CONSTRAINT "fk_hygiene_fix_overdue_notices_ticket_id" FOREIGN KEY ("ticket_id") REFERENCES "hygiene_fix_tickets"("id");
ALTER TABLE "hygiene_fix_reshoots" ADD CONSTRAINT "fk_hygiene_fix_reshoots_ticket_id" FOREIGN KEY ("ticket_id") REFERENCES "hygiene_fix_tickets"("id");
ALTER TABLE "hygiene_fix_tickets" ADD CONSTRAINT "fk_hygiene_fix_tickets_zone_id" FOREIGN KEY ("zone_id") REFERENCES "hygiene_zones"("id");
ALTER TABLE "hygiene_overdue_notices" ADD CONSTRAINT "fk_hygiene_overdue_notices_item_id" FOREIGN KEY ("item_id") REFERENCES "hygiene_daily_items"("id");
ALTER TABLE "hygiene_shift_picks" ADD CONSTRAINT "fk_hygiene_shift_picks_employee_id" FOREIGN KEY ("employee_id") REFERENCES "hygiene_employees"("id");
ALTER TABLE "hygiene_staff_sessions" ADD CONSTRAINT "fk_hygiene_staff_sessions_employee_id" FOREIGN KEY ("employee_id") REFERENCES "hygiene_employees"("id");
ALTER TABLE "hygiene_standards" ADD CONSTRAINT "fk_hygiene_standards_item_id" FOREIGN KEY ("item_id") REFERENCES "hygiene_daily_items"("id");
ALTER TABLE "sop_recipes" ADD CONSTRAINT "fk_sop_recipes_station_slug" FOREIGN KEY ("station_slug") REFERENCES "sop_stations"("slug") ON DELETE CASCADE;
ALTER TABLE "sop_recipes_history" ADD CONSTRAINT "fk_sop_recipes_history_station_slug" FOREIGN KEY ("station_slug") REFERENCES "sop_stations"("slug") ON DELETE CASCADE;

COMMIT;
