-- 0004：运行日志表（logs）进 PostgreSQL
--
-- 背景（ADR 0089）：`data/logs.db` 是最后一个 SQLite 依赖——日志库独立于业务库，
-- 一直是 aiosqlite + WAL + 损坏隔离那一套。SQLite 退场后日志表进 PG，与业务表
-- 同库；WAL/quick_check/损坏隔离/forensics 这些 SQLite 专有语义随之下线。
--
-- 幂等：IF NOT EXISTS，可重复执行。
--
-- ts_epoch 用 DOUBLE PRECISION（沿用 SQLite 的 REAL 语义，秒级浮点时间戳），
-- 让 `_build_where` 的时间窗比较与 `ORDER BY ts_epoch DESC` 保持一致。

CREATE TABLE IF NOT EXISTS logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,
    ts_epoch DOUBLE PRECISION NOT NULL,
    level TEXT NOT NULL,
    logger TEXT NOT NULL,
    message TEXT NOT NULL,
    exception TEXT
);

CREATE INDEX IF NOT EXISTS idx_logs_ts_epoch ON logs (ts_epoch DESC);
CREATE INDEX IF NOT EXISTS idx_logs_level ON logs (level);
CREATE INDEX IF NOT EXISTS idx_logs_logger ON logs (logger);
