-- 0005：排班系统第一批表（班次 / 轮转规则 / 排班结果）
--
-- 背景：排班是**独立系统**（`.scratch/scheduling/spec.md`），跟卫生平级，两边代码
-- 不互相 import，只共享公共层的员工身份。排班把规则算成结果、**物化**进
-- `staff_assignments`；下游（员工端、卫生）只读那份数据 —— 「谁是上游」是数据上的
-- 事实，不是调用关系。
--
-- 幂等：IF NOT EXISTS / ON CONFLICT DO NOTHING，可重复执行。
--
-- 沿用仓库既有口径：时间戳 TEXT（ISO 字符串，带 +08:00）、布尔用 BIGINT 0/1
-- （同 `hygiene_employees.approved`/`disabled`）。班次**没有起止时刻**：一个营业日
-- 上挂一个班次值，工时/迟到/打卡都不进来（spec 的 Out of Scope）。

CREATE TABLE IF NOT EXISTS staff_shifts (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "sort_order" BIGINT NOT NULL DEFAULT 0,
    "is_active" BIGINT NOT NULL DEFAULT 1,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "name")
);

-- 算出来的结果：谁在哪天、上什么班、在哪个区。
-- `shift_id IS NULL` = 那天休（规则里 `NULL` 那一格）；`zone_id` 由排班写、
-- 本期（票 02）一律为 NULL，等工作区默认值那张表落地后填。
-- `source` 记这一行是谁写的：`rule`（规则展开）/ `override`（单日改写，后面的票）。
CREATE TABLE IF NOT EXISTS staff_assignments (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employee_id" BIGINT NOT NULL,
    "business_date" TEXT NOT NULL,
    "shift_id" BIGINT,
    "zone_id" BIGINT,
    "source" TEXT NOT NULL DEFAULT 'rule',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "employee_id", "business_date")
);

-- 月历按天聚合（`GROUP BY business_date`），唯一键是 (employee_id, business_date)，
-- 帮不到这个方向，单给一条。前导列不写 tenant_id：单店阶段它恒为 1，前缀等于白占
-- （migrations/pg/README.md 的「索引暂不以 tenant_id 为前导列」）。
CREATE INDEX IF NOT EXISTS idx_staff_assignments_date
    ON staff_assignments (business_date);

-- 一人一条轮转规则。`cycle` 是 JSON 数组的文本：长度 = 周期天数、每格是班次 id、
-- `null` 表示休（「白白白夜夜休休」= [白,白,白,夜,夜,null,null]）。`anchor_date`
-- 是周期起点，相位由它和营业日之差算出来。
CREATE TABLE IF NOT EXISTS scheduling_rules (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employee_id" BIGINT NOT NULL,
    "cycle" TEXT NOT NULL,
    "anchor_date" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "employee_id")
);

-- 两个默认班次。**这是给装完就看的**：应用启动时 `SchedulingStore.prepare()` 还会在
-- 「表为空」时放同一组默认值（测试库每个用例都会 TRUNCATE，seed 留不住；改过名的店
-- 重启也不该被变回来，所以那边是「只在空表时写」）。
INSERT INTO staff_shifts (tenant_id, id, name, sort_order, is_active, created_at, updated_at)
VALUES
    (1, 1, '白班', 10, 1,
     to_char(now() + interval '8 hours', 'YYYY-MM-DD"T"HH24:MI:SS') || '+08:00',
     to_char(now() + interval '8 hours', 'YYYY-MM-DD"T"HH24:MI:SS') || '+08:00'),
    (1, 2, '夜班', 20, 1,
     to_char(now() + interval '8 hours', 'YYYY-MM-DD"T"HH24:MI:SS') || '+08:00',
     to_char(now() + interval '8 hours', 'YYYY-MM-DD"T"HH24:MI:SS') || '+08:00')
ON CONFLICT DO NOTHING;

-- 显式写 id 不会推进 identity 序列（migrations/pg/README.md 的「导入数据后必须重置
-- identity 序列」），不重置的话下一个不带 id 的 INSERT 会撞主键。
SELECT setval(
    pg_get_serial_sequence('staff_shifts', 'id'),
    GREATEST((SELECT MAX(id) FROM staff_shifts), 1)
);
