-- 0006：每人每班次一个固定工作区（票 03）
--
-- 背景：工作区名单本来只有卫生用（`hygiene_zones`，建区时勾「跑不跑白班/夜班」），
-- 人跟区的关系只存在于卫生的**当日**分工里（`hygiene_shift_picks.zone_id`，当天自己选）。
-- 排班定下来的口径是「**每个班次一个固定区，跟人走**」：白班在案板的人就一直排案板，
-- 所以这份「谁 × 哪个班次 × 哪个区」的配置要在排班这边落成数据。
--
-- 名单本身**不搬表**：`hygiene_zones` 仍是唯一的区名单，两边各读各的 —— 排班通过
-- 公共层的 `services/identity/zones.py`（ZoneDirectory）读它，不 import 卫生的任何代码。
-- 这张新表只存三件事：哪个人、哪个班次、哪个区。
--
-- 幂等：IF NOT EXISTS，可重复执行。时间戳 TEXT（ISO 字符串，带 +08:00），沿用仓库既有口径。
--
-- `zone_id` 可为 NULL：表示「这个人这个班次还没定在哪」—— 一个正常状态，不是错误。
-- 与 0005 的 `staff_assignments.zone_id` 之分：那边的 `zone_id` 是**那天写下来的结果**
-- （过去一行不改），这边是**现在的配置**（改了会把今天以后还没过的行一起改掉）。

CREATE TABLE IF NOT EXISTS scheduling_zone_defaults (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employee_id" BIGINT NOT NULL,
    "shift_id" BIGINT NOT NULL,
    "zone_id" BIGINT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "employee_id", "shift_id")
);

-- 上面那条唯一键的**前导列是 tenant_id**，而单店阶段代码里根本不带租户条件
-- （`services/scheduling/store.py` 全文没有 tenant_id），所以「按人取固定区」这个
-- 方向用不上它。另给一条前导列是 employee_id 的，口径同 0005 的
-- `idx_staff_assignments_date`（`migrations/pg/README.md` 的「索引暂不以 tenant_id
-- 为前导列」）。
CREATE INDEX IF NOT EXISTS idx_scheduling_zone_defaults_employee
    ON scheduling_zone_defaults (employee_id, shift_id);
