-- 0007：单日覆盖（票 07）
--
-- 背景：`staff_assignments` 的行原本只有一种来源 —— 规则铺出来的（`source='rule'`）。
-- 店长要能把**某一天**改掉：今天小李不来了、那天他改上夜班、那天他换个区。
-- 这种改动不能碰规则（明天后天照旧），也不能只活在界面上（下游卫生读的是这张表）。
--
-- 所以这是**第二份输入**（第一份是 `scheduling_rules`）：一人一天最多一条覆盖记录，
-- 它记的是「这一天跟规则不一样，不一样成什么」。规则展开时遇到有覆盖的天，
-- 按覆盖写；改规则时也不动那天的行（`services/scheduling/store.py` 的
-- `_delete_future_rule_rows` 只删 `source='rule'` 的行）——
-- 「改规则不该冲掉手改过的那天」是这条 `source` 判据的结果。
--
-- 覆盖是**整天的快照**（班次 + 责任区一起定下来），不是「只冻结班次」那种半份。
-- 「只改责任区」也走这里：提交时带着当天那个班次、只换区 —— 一份口径，不用记「这次改的是
-- 哪一半」。代价写在票面上：规则以后变了，手改过的那天不跟着变（撤掉覆盖才回到规则）。
--
-- `shift_id IS NULL` = 那天休，与 `staff_assignments` 同一口径（0005 的注释）。
-- `kind` 记这一行是谁写的：`manual`（店长在月历上点着改的，本票唯一会写的值）；
-- 票 08 的请假、票 09 的换班各写各的值 —— 那天为什么不一样要能分得清。
--
-- 幂等：IF NOT EXISTS，可重复执行。时间戳 TEXT（ISO 字符串，带 +08:00），沿用仓库既有口径。

CREATE TABLE IF NOT EXISTS scheduling_overrides (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employee_id" BIGINT NOT NULL,
    "business_date" TEXT NOT NULL,
    "shift_id" BIGINT,
    "zone_id" BIGINT,
    "kind" TEXT NOT NULL DEFAULT 'manual',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "employee_id", "business_date")
);

-- 上面那条唯一键的前导列是 tenant_id，单店阶段代码里不带租户条件
-- （`services/scheduling/store.py` 全文没有 tenant_id），所以它对下面这些查询用不上。
-- 代码里碰这张表的非 INSERT 语句一共四条，按访问路径算正好三条，前导列都是 employee_id：
-- `_apply_override`（`employee_id = ? AND business_date = ?` 查一次，再 INSERT 或 UPDATE）、
-- `_clear_override`（同样的等值条件查一次，再 DELETE）与
-- `_expand_rows`（`employee_id = ? AND business_date >= ? AND business_date <= ?`，铺规则前先看有没有覆盖）；
-- **没有**按 `business_date` 单独筛的查询，所以索引前导列跟着访问路径走，口径同 0006 给自己
-- 加的 `idx_scheduling_zone_defaults_employee`（`migrations/pg/README.md` 的「索引暂不以
-- tenant_id 为前导列」）。
CREATE INDEX IF NOT EXISTS idx_scheduling_overrides_employee
    ON scheduling_overrides (employee_id, business_date);
