-- 0008：请假申请（票 08）
--
-- 背景：请假原本只能口头说 —— 谁提的、店长批没批、那几天到底算不算数，全都没有记录。
-- 这张表记「员工提的一次申请」：一天或一段日子（`start_date`..`end_date`，**两端都算**）。
-- 状态机照 `spec.md` 固定下来的那套：`pending_manager`（等店长批）→ `approved` / `rejected`，
-- 申请人自己撤回落到 `cancelled`；`pending_peer` 是票 09 的换班专用，请假不经过它。
--
-- 批了之后**请假这个标记的出处是覆盖表**：给区间里每一天写一条覆盖
-- （`kind = 'leave'`、`shift_id IS NULL`），排班结果那几天就变成请假。
-- 结果行不新增列：批过的那几天照票 07 那条路走（`source = 'override'`、`shift_id IS NULL`），
-- 于是请假与本来就休在结果表里同形，区别记在覆盖记录的 `kind` 上（0007 定的列）。
-- 但要说清：**批假确实会改结果行** —— 原本上白班的人被批假后，那几行会变成没有班次。
-- 驳回与撤回**一个字都不写进排班结果**（「驳回后排班不变」是验收项）。
--
-- 幂等：IF NOT EXISTS，可重复执行。时间戳 TEXT（ISO 字符串，带 +08:00），沿用仓库既有口径。

CREATE TABLE IF NOT EXISTS scheduling_requests (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employee_id" BIGINT NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'leave',
    "start_date" TEXT NOT NULL,
    "end_date" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending_manager',
    "note" TEXT,
    "decided_at" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

-- 两条访问路径，索引一条对一条：店长待办读「所有等店长批的申请」（`status = ?`，按提交时间排），
-- 员工页读「我自己的申请」（`employee_id = ?`，按提交时间倒序）。没有按日期区间单独筛的查询
-- （待办卡片上的人手提示是按申请人算的，不是按天捞申请），所以日期列不进索引。
-- 前导列不带 tenant_id 的理由同 0007（单店阶段代码里没有租户条件）。
CREATE INDEX IF NOT EXISTS idx_scheduling_requests_status
    ON scheduling_requests (status, created_at);

CREATE INDEX IF NOT EXISTS idx_scheduling_requests_employee
    ON scheduling_requests (employee_id, created_at);
