-- 0011：仪容仪表拍照（按人，排到班次才要拍）
--
-- 背景：卫生现有的三类活（日常 / 专项 / 整改）都挂在**责任区**上；仪容仪表是**按人**的
-- 事：今天排到班次的员工各拍一张，休假的与没排到的不用拍（判据是排班
-- `staff_assignments` 那天 `shift_id IS NOT NULL`，经公共层 `DutyRoster` 读）。
--
-- 两张表：
--
-- `hygiene_attire_shots` —— 一个人一个营业日一行。状态机跟日常一样：
--   `todo`（还没拍，行是懒建的）→ `pending`（拍了等验收）→ `passed` / `rejected`。
--   重拍覆盖「等验收」那一张（同一天只有一行，`UNIQUE` 兜住）。
--   `shift_id` 是**拍的时候**排到的那条班次：留档用，排班后面改了不影响这天。
--   `note` 是驳回原因（跟日常驳回同一条口径：写清为止，员工照它重拍）。
--
-- `hygiene_attire_standard` —— 标准图。跟 `hygiene_standards`（按检查项）不是一个形状：
--   仪容仪表不分项、只有一张。每次上传**插一行**，读的时候取最新那条（跟日常标准图
--   「新版本是新行」一个口径，旧版本留着，谁也不去改历史）。
--
-- 没有钟点列：这一项**不设截止时间**（用户口径），所以没有 overdue 那一套。
--
-- 幂等：IF NOT EXISTS，可重复执行。

CREATE TABLE IF NOT EXISTS hygiene_attire_shots (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employee_id" BIGINT NOT NULL,
    "business_date" TEXT NOT NULL,
    "shift_id" BIGINT,
    "status" TEXT NOT NULL DEFAULT 'todo',
    "capture_id" TEXT NOT NULL,
    "note" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    UNIQUE ("tenant_id", "employee_id", "business_date")
);

-- 管理员那一侧的主要访问路径：某一天、按状态捞（待验收 / 已通过 / 驳回）。
CREATE INDEX IF NOT EXISTS idx_hygiene_attire_date
    ON hygiene_attire_shots (business_date, status);

CREATE TABLE IF NOT EXISTS hygiene_attire_standard (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "capture_id" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "markup_json" TEXT NOT NULL DEFAULT '[]',
    "byte_size" BIGINT,
    "content_sha256" TEXT,
    "created_at" TEXT NOT NULL
);
