-- 0013：验收照片进群的分享记录（幂等 + 重试队列）
--
-- 背景：验收通过的实拍要自动发到卫生群（企业微信群机器人）。发送是网络 IO（webhook
-- 10 秒超时），**不能**放在验收的写锁里 —— 一张 12MP 照片的解码都嫌久，何况等一个
-- 外部 HTTP。所以拆成两步：验收的事务里只登记一行 `pending`（与验收同生共死，
-- 不存在"验收成功了但没登记"），真正的发送由进程内串行 flush 在锁外做。
--
-- `dedupe_key` = 业务类型 + 业务引用 + 采集图 id，唯一约束保证**同一张照片只发一次**：
-- 重复点验收、弱网重传都不会刷屏；员工重拍后再次通过是新的采集图，因此会再发一次
-- （这正是想要的）。
--
-- 状态机：`pending`（待发，会被 flush 捡起）→ `sent`（已发）/ `skipped`（没有启用中的
-- 卫生群，不再重试，也不会在以后勾了群之后突然补发旧照片）/ `failed`（重试用尽）。
-- `attempts` 与 `last_error` 留给排查。
--
-- 加成性变更 + 幂等：IF NOT EXISTS，可重复执行。

CREATE TABLE IF NOT EXISTS hygiene_wecom_shares (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "kind" TEXT NOT NULL,
    "ref_key" TEXT NOT NULL,
    "capture_id" TEXT NOT NULL,
    "dedupe_key" TEXT NOT NULL,
    "caption" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'pending',
    "attempts" BIGINT NOT NULL DEFAULT 0,
    "last_error" TEXT NOT NULL DEFAULT '',
    "created_at" TEXT NOT NULL,
    "sent_at" TEXT,
    UNIQUE ("tenant_id", "dedupe_key")
);

-- flush 只捞 pending，按 id 先进先出。
CREATE INDEX IF NOT EXISTS idx_hygiene_wecom_shares_pending
    ON hygiene_wecom_shares (status, id);
