-- 0016：推送订阅 / 渠道群组 / 群组成员 / 出站记录，并回填现有收件人
--
-- 背景（ADR 0094）：出站消息的收件人原先散在三处 —— 定时任务绑定单个渠道
-- （`wecom_push_jobs.webhook_id`）、渠道上的 `hygiene_feed` 布尔列决定卫生提醒与
-- 验收照片、采集告警直接广播给**所有启用渠道**。每加一类内容就要加一列或复制一条
-- 任务。改为：内容类型由后端注册表声明，「谁收到什么」只有一条真相来源 ——
-- **推送订阅**（内容类型 × 目标，目标是推送渠道或渠道群组）。
--
-- 本脚本做三件事，缺一不可：
--   1. 建四张新表（订阅 / 群组 / 群组成员 / 出站记录）；
--   2. 按**三条规则**把现有配置回填成订阅，使上线瞬间每类内容的目标渠道与迁移前
--      逐条一致 —— 迁移本身不改变任何一封消息的收件人；
--   3. 把历史发送记录（`wecom_push_logs`）与照片分享历史（`hygiene_wecom_shares`）
--      一次性搬进出站表（ADR 0095：队列表与发送记录是同一张表）。
--
-- 旧列与旧表**原样保留、只读**：`hygiene_feed` 不再被新代码读取，旧表继续可查。
--
-- 内容类型 id（字符串，第二批的注册表把这些 id 与显示名 / 参数 schema 一起声明）：
--   sales_report        销售报表            （定时）
--   reconcile_diff      对账差异告警        （定时 + 事件，定时侧承载原「数据质量日报」）
--   unmapped_dish       未映射菜品提醒      （事件）
--   scraper_failure     采集失败告警        （事件）
--   hygiene_reminder    卫生提醒            （事件）
--   hygiene_photo       验收照片            （事件，含员工实拍照片）
--   update_backup       系统更新与备份结果  （事件）
--   resource_watermark  磁盘与内存水位      （事件）
--
-- 加成性变更 + 幂等：IF NOT EXISTS / ON CONFLICT DO NOTHING，可重复执行。
-- （回填语句是纯 INSERT…SELECT，重跑只会撞唯一索引后跳过，不会翻倍。）


-- ── 表 ──────────────────────────────────────────────────────────────────────

-- 渠道群组：若干渠道的集合，可以整体被订阅，同时是管理页面上的分组。
-- （先于订阅表建：订阅的目标列引用它。）
CREATE TABLE IF NOT EXISTS wecom_channel_groups (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "enabled" BIGINT NOT NULL DEFAULT 1,
    "notes" TEXT NOT NULL DEFAULT '',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_wecom_channel_groups_name
    ON wecom_channel_groups (tenant_id, name);

-- 推送订阅：一行 = 「某类内容发给某个渠道**或**某个群组」。
-- 两个目标列恰好有一个非空（CHECK）；两条局部唯一索引保证同一目标不会被订两次，
-- 也让回填可以写成 ON CONFLICT DO NOTHING（表达式索引做冲突目标时推断容易出错，
-- 拆成两条带 WHERE 的唯一索引更稳）。
CREATE TABLE IF NOT EXISTS wecom_push_subscriptions (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "topic_id" TEXT NOT NULL,
    "target_channel_id" BIGINT REFERENCES wecom_push_webhooks(id) ON DELETE CASCADE,
    "target_group_id" BIGINT REFERENCES wecom_channel_groups(id) ON DELETE CASCADE,
    "enabled" BIGINT NOT NULL DEFAULT 1,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT wecom_push_subscriptions_one_target CHECK (
        (target_channel_id IS NULL) <> (target_group_id IS NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_wecom_push_subscriptions_channel
    ON wecom_push_subscriptions (tenant_id, topic_id, target_channel_id)
    WHERE target_channel_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_wecom_push_subscriptions_group
    ON wecom_push_subscriptions (tenant_id, topic_id, target_group_id)
    WHERE target_group_id IS NOT NULL;

-- 订阅求解要按内容类型一次取全（页面矩阵也是这个形状）。
CREATE INDEX IF NOT EXISTS idx_wecom_push_subscriptions_topic
    ON wecom_push_subscriptions (tenant_id, topic_id, enabled);

-- 群组成员：一个渠道可以属于多个群组（「日报群组」与「门店 A」并存）。
CREATE TABLE IF NOT EXISTS wecom_channel_group_members (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "group_id" BIGINT NOT NULL REFERENCES wecom_channel_groups(id) ON DELETE CASCADE,
    "channel_id" BIGINT NOT NULL REFERENCES wecom_push_webhooks(id) ON DELETE CASCADE,
    "created_at" TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_wecom_channel_group_members_pair
    ON wecom_channel_group_members (tenant_id, group_id, channel_id);

CREATE INDEX IF NOT EXISTS idx_wecom_channel_group_members_channel
    ON wecom_channel_group_members (channel_id);

-- 出站记录：**一次投递一行**（ADR 0095），队列表与发送记录是同一张表。
-- 行里存内容类型 + 参数 + 目标，正文在发送时渲染（照片存采集图引用，不存 base64）。
-- 状态：pending 待发 → sending 发送中 → sent 已发 / failed 失败 / skipped 跳过。
CREATE TABLE IF NOT EXISTS wecom_push_outbox (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "topic_id" TEXT NOT NULL,
    "params_json" TEXT NOT NULL DEFAULT '{}',
    "schedule_id" BIGINT,
    "target_channel_id" BIGINT REFERENCES wecom_push_webhooks(id) ON DELETE SET NULL,
    "content_summary" TEXT NOT NULL DEFAULT '',
    "message_bytes" BIGINT NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "attempts" BIGINT NOT NULL DEFAULT 0,
    "last_error" TEXT NOT NULL DEFAULT '',
    "idempotency_key" TEXT NOT NULL,
    "scheduled_at" TEXT,
    "created_at" TEXT NOT NULL,
    "finished_at" TEXT
);

-- 幂等键 = 内容类型 + 业务引用 + 目标：同一张采集图 / 同一天同一渠道的同类投递
-- 只落一行（「只发一次」靠这条唯一索引兜底）。
CREATE UNIQUE INDEX IF NOT EXISTS idx_wecom_push_outbox_idempotency
    ON wecom_push_outbox (tenant_id, idempotency_key);

-- 调度循环只捞待发，先进先出。
CREATE INDEX IF NOT EXISTS idx_wecom_push_outbox_pending
    ON wecom_push_outbox (status, id);

-- 发送记录页的筛选（内容类型 / 渠道 / 状态）与保留清理都按时间倒序。
CREATE INDEX IF NOT EXISTS idx_wecom_push_outbox_topic_created
    ON wecom_push_outbox (tenant_id, topic_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_wecom_push_outbox_channel_created
    ON wecom_push_outbox (tenant_id, target_channel_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_wecom_push_outbox_status_created
    ON wecom_push_outbox (tenant_id, status, created_at DESC);


-- ── 回填：三条规则 ──────────────────────────────────────────────────────────
--
-- 三条规则缺一不可（spec「迁移与上线」）：
--   ① `hygiene_feed = 1` 的渠道 → 卫生类（卫生提醒、验收照片）；
--   ② 所有**启用**渠道 → 采集类（对账差异、未映射菜品、采集失败）；
--   ③ 每条现有推送任务的「内容类型 × 它绑定的渠道」→ 该内容类型的订阅。
--
-- 规则③ 是三条里最容易漏的一条：推送任务不再持有收件人之后，这条订阅就是它原来的
-- 收件人，漏掉它等于日报不再发给原来的群。
--
-- 回填不筛 `enabled`（除规则② 明确要求「启用渠道」）：渠道停用只跳过投递，订阅本身
-- 保留 —— 店长恢复启用后不用重配（spec 用户故事 7）。

-- ① 卫生群：卫生提醒 + 验收照片各一行。
INSERT INTO wecom_push_subscriptions
    (tenant_id, topic_id, target_channel_id, enabled, created_at, updated_at)
SELECT w.tenant_id, t.topic_id, w.id, 1,
       to_char(now() AT TIME ZONE 'Asia/Shanghai', 'YYYY-MM-DD"T"HH24:MI:SS')
           || '+08:00',
       to_char(now() AT TIME ZONE 'Asia/Shanghai', 'YYYY-MM-DD"T"HH24:MI:SS')
           || '+08:00'
  FROM wecom_push_webhooks w
  CROSS JOIN (VALUES ('hygiene_reminder'), ('hygiene_photo')) AS t(topic_id)
 WHERE w.hygiene_feed = 1
ON CONFLICT DO NOTHING;

-- ② 采集告警：所有启用渠道，三类内容各一行。
INSERT INTO wecom_push_subscriptions
    (tenant_id, topic_id, target_channel_id, enabled, created_at, updated_at)
SELECT w.tenant_id, t.topic_id, w.id, 1,
       to_char(now() AT TIME ZONE 'Asia/Shanghai', 'YYYY-MM-DD"T"HH24:MI:SS')
           || '+08:00',
       to_char(now() AT TIME ZONE 'Asia/Shanghai', 'YYYY-MM-DD"T"HH24:MI:SS')
           || '+08:00'
  FROM wecom_push_webhooks w
  CROSS JOIN (VALUES ('reconcile_diff'), ('unmapped_dish'), ('scraper_failure'))
       AS t(topic_id)
 WHERE w.enabled = 1
ON CONFLICT DO NOTHING;

-- ③ 现有推送任务原来绑定的渠道 → 它那个内容类型的订阅。
-- 旧 push_type 与新内容类型 id 的对照：只有两个值对不上（见 tests 里的字面量断言）：
--   sales_report_text   → sales_report
--   data_quality_alert  → reconcile_diff   （对账差异 + 未映射菜品 + 采集失败摘要）
INSERT INTO wecom_push_subscriptions
    (tenant_id, topic_id, target_channel_id, enabled, created_at, updated_at)
SELECT w.tenant_id, m.topic_id, w.id, 1,
       to_char(now() AT TIME ZONE 'Asia/Shanghai', 'YYYY-MM-DD"T"HH24:MI:SS')
           || '+08:00',
       to_char(now() AT TIME ZONE 'Asia/Shanghai', 'YYYY-MM-DD"T"HH24:MI:SS')
           || '+08:00'
  FROM wecom_push_jobs j
  JOIN wecom_push_webhooks w ON w.id = j.webhook_id
  JOIN (VALUES ('sales_report_text', 'sales_report'),
               ('data_quality_alert', 'reconcile_diff')) AS m(legacy_type, topic_id)
    ON m.legacy_type = j.push_type
ON CONFLICT DO NOTHING;


-- ── 历史行搬入出站表 ────────────────────────────────────────────────────────
--
-- 旧表保留只读；搬进来的行带 `legacy:` 前缀的幂等键，重跑不会翻倍。
-- 字段一一对应，不丢：状态 / 目标渠道 / 时间 / 错误 / 字节数 / 尝试次数。

-- 定时推送的发送记录。旧日志没有 attempts 列：旧链路**没有重试**，所以每行按
-- 「尝试过 1 次」记录（终态行），如实反映旧行为，而不是编造重试次数。
--
-- 孤儿引用：`wecom_push_logs.webhook_id` 没有外键，渠道删掉之后历史行会留下指向
-- 已不存在渠道的 id（真库上就有）。出站表的目标列**有**外键，直接搬会让整条迁移
-- 失败，所以这类行搬成「没有目标」的行，原渠道 id 留在参数里备查。
INSERT INTO wecom_push_outbox
    (tenant_id, topic_id, params_json, schedule_id, target_channel_id,
     content_summary, message_bytes, status, attempts, last_error,
     idempotency_key, scheduled_at, created_at, finished_at)
SELECT l.tenant_id,
       COALESCE(m.topic_id, l.push_type),
       CASE WHEN w.id IS NULL AND l.webhook_id IS NOT NULL
            THEN json_build_object('legacy_webhook_id', l.webhook_id)::text
            ELSE '{}'
       END,
       l.job_id,
       w.id,
       left(COALESCE(NULLIF(l.response_text, ''), l.error, ''), 200),
       l.message_bytes,
       CASE l.status WHEN 'success' THEN 'sent' ELSE 'failed' END,
       1,
       COALESCE(l.error, ''),
       'legacy:log:' || l.id,
       l.sent_at,
       l.sent_at,
       l.sent_at
  FROM wecom_push_logs l
  LEFT JOIN wecom_push_webhooks w ON w.id = l.webhook_id
  LEFT JOIN (VALUES ('sales_report_text', 'sales_report'),
                    ('data_quality_alert', 'reconcile_diff'),
                    ('hygiene_photo', 'hygiene_photo')) AS m(legacy_type, topic_id)
    ON m.legacy_type = l.push_type
ON CONFLICT DO NOTHING;

-- 验收照片的分享历史。旧实现往**每个**卫生群各发一份，出站表是「一次投递一行」，
-- 而这一趟只搬一行：未发出去的分享（`pending`）目标指向当时的一个卫生群，让它可以
-- 被调度循环接着发；已终结的行（`sent` / `failed` / `skipped`）目标只作留档，本来就
-- 不会再投递。当时一个卫生群都没有的行目标为空（`skipped`：没有收件人，不会补发），
-- 保留历史而不假装它有过收件人。
INSERT INTO wecom_push_outbox
    (tenant_id, topic_id, params_json, schedule_id, target_channel_id,
     content_summary, message_bytes, status, attempts, last_error,
     idempotency_key, scheduled_at, created_at, finished_at)
SELECT s.tenant_id,
       'hygiene_photo',
       json_build_object(
           'ref_key', s.ref_key,
           'capture_id', s.capture_id,
           'extra_capture_id', s.extra_capture_id
       )::text,
       NULL,
       g.id,
       left(s.caption, 200),
       0,
       CASE s.status
            WHEN 'sent' THEN 'sent'
            WHEN 'failed' THEN 'failed'
            WHEN 'skipped' THEN 'skipped'
            ELSE 'pending'
       END,
       s.attempts,
       COALESCE(s.last_error, ''),
       'legacy:share:' || s.id || ':' || COALESCE(g.id::text, 'none'),
       NULL,
       s.created_at,
       CASE WHEN s.status = 'sent' THEN s.sent_at ELSE NULL END
  FROM hygiene_wecom_shares s
  LEFT JOIN LATERAL (
      SELECT w.id
        FROM wecom_push_webhooks w
       WHERE w.enabled = 1 AND w.hygiene_feed = 1
       ORDER BY w.id
       LIMIT 1
  ) AS g ON true
ON CONFLICT DO NOTHING;
