-- 0019：推送配置的变更历史（审计表）
--
-- 背景（spec「鉴权与审计」，票 11）：这一页的写操作（渠道 / 群组 / 成员 / 订阅 /
-- 任务）原先一个字都不留痕 —— 谁在什么时候把某个群停用了、把哪条订阅取消了，
-- 事后只能靠翻应用日志猜。本脚本建一张**只追加**的表，让「谁改了什么、改前是什么
-- 样」在页面的「变更历史」tab 里可查。
--
-- 设计取舍（写在这里，是因为它们只由这张表的形状决定）：
--
--   1. `before_json` / `after_json` 存**领域字段**的快照（名称 / 启停 / 备注 /
--      订阅目标……），不存整行，也不存 webhook 地址的密文或明文 —— 审计要能读出
--      「改了什么」，但不该成为第二份凭据存储。地址的变更只以掩码（`url` 字段）
--      出现在快照里。
--   2. 快照是**当时**的文本，不是外键：渠道删掉之后那条记录仍要读得出来。所以
--      这里**没有**指向 `wecom_push_webhooks` 的外键，`object_id` 只是标识符。
--   3. `actor` 是登录账号名（当前管理后台只有一个管理员，`admin_user` id=1）。
--      取不到名字时留空串：审计缺一条人名，不该让原本成功的配置变更报错。
--   4. **长期保留**：这张表不参与发送记录（出站表）的 90 天清理，也没有自己的
--      保留期 —— 配置变更历史的价值恰恰在半年后回看。清理入口一个都没有。
--
-- 动作取值（`action`）：create / update / enable / disable / delete
-- 对象类型（`object_type`）：wecom_push_webhooks / wecom_channel_groups /
--                             wecom_push_subscriptions / wecom_push_jobs
--
-- 加成性变更 + 幂等：IF NOT EXISTS，可重复执行（管理员在「数据库迁移」面板上重跑
-- 一次不会报错，也不会清掉已有记录）。

CREATE TABLE IF NOT EXISTS wecom_push_audit (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TEXT NOT NULL,
    "actor" TEXT NOT NULL DEFAULT '',
    "action" TEXT NOT NULL,
    "object_type" TEXT NOT NULL,
    "object_id" BIGINT,
    "object_name" TEXT NOT NULL DEFAULT '',
    "before_json" TEXT NOT NULL DEFAULT '{}',
    "after_json" TEXT NOT NULL DEFAULT '{}'
);

-- 页面默认就是「按时间倒序看最近发生了什么」，所以主索引与它逐字一致。
CREATE INDEX IF NOT EXISTS idx_wecom_push_audit_created
    ON wecom_push_audit (tenant_id, created_at DESC, id DESC);

-- 「变更历史」tab 上唯一的筛选项是对象类型，索引跟着它走。
CREATE INDEX IF NOT EXISTS idx_wecom_push_audit_object_type
    ON wecom_push_audit (tenant_id, object_type, created_at DESC, id DESC);
