-- 0021：加班与补钟登记（票 01）
--
-- 背景：员工加班、欠钟（补钟）此前只在群里说或纸上记 —— 谁提的、批没批、这个月
-- 累计多少小时，全都没有记录。这张表就是那本台账（`.scratch/overtime-and-reminders/`）。
--
-- 一条记录 = 一个**自然日** + 一个**带符号的小时数** + 必填事由：加班为正、补钟为负。
-- **不存 kind**：符号就是类型（见 `CONTEXT.md` 的「加班与补钟登记」）。时长按
-- **半小时为单位**存整数（`half_hours`）：0.5 小时是界面的步长，整数存就没有浮点
-- 误差 —— 与 0020 的 `base_salary` 用 BIGINT 同一个理由。±24 = ±12 小时（单条上限）。
--
-- 状态机（`docs/adr/0100-overtime-and-makeup-ledger.md`）：`pending` → `approved` /
-- `rejected` / `cancelled`，`approved` 还能被超级管理员 `voided`。本票只用得到
-- `pending` 与 `cancelled`（提交与撤回），审批那一半在票 02。
--
-- `created_by` 记的是「谁把这一条提上来的」：`super`（管理端共享账号）或
-- `staff:<员工号>`。代员工补录时写的是**代录人**，`employee_id` 才是这笔算谁的。
--
-- 幂等：IF NOT EXISTS，可重复执行。时间戳 TEXT（ISO 字符串，带 +08:00），沿用仓库口径。

CREATE TABLE IF NOT EXISTS overtime_entries (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employee_id" BIGINT NOT NULL,
    "entry_date" TEXT NOT NULL,
    "half_hours" BIGINT NOT NULL,
    "reason" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "reject_reason" TEXT,
    "created_by" TEXT NOT NULL,
    "decided_by" TEXT,
    "decided_at" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT overtime_entries_half_hours_not_zero CHECK ("half_hours" <> 0)
);

-- 三条访问路径，索引一条对一条：待办读「所有等审批的」（按状态与提交时间），员工页读
-- 「我自己的」（按人按日期，也供按月统计走），全店按月统计按日期领头读。
-- 前导列不带 tenant_id 的理由同 0007/0008（单店阶段代码里没有租户条件）。
CREATE INDEX IF NOT EXISTS idx_overtime_entries_status
    ON overtime_entries (status, created_at);

CREATE INDEX IF NOT EXISTS idx_overtime_entries_employee
    ON overtime_entries (employee_id, entry_date);

CREATE INDEX IF NOT EXISTS idx_overtime_entries_date
    ON overtime_entries (entry_date);
