-- 0023：工龄奖（票 05）
--
-- 背景：工龄奖（满一年 100、两年 200 …… 第 10 年 1000 封顶）此前没有载体 —— 规则
-- 只活在人的脑子里，谁该调、调没调、有没有漏，没有任何地方说得清。这条迁移加两样：
--
-- 1. `hygiene_employees.seniority_bonus`：这个人的**当前**工龄奖（元/月，整数，可空）。
--    「应为」值是**派生**的（按入职日期算，唯一实现在 `services/identity/profile.py`），
--    这里存的是**人工落账**的那一份 —— 两者不一致是合法状态，绝不自动改写
--    （`docs/adr/0101-seniority-bonus-month-and-ledger.md`）。
--    **它不进「待补」四项**（`profile.py` 的 `PROFILE_FIELDS`）：空值的意思是
--    「还没调过」，不是「档案缺一项」，它也不挡批准员工。
--
-- 2. `seniority_bonus_changes`：每一次改动的留痕（谁、何时、从多少到多少）。
--    它是**钱**的台账，所以刻意不写进 `logs` 表 —— 那张表按保留天数清理，而这条
--    不该消失。只追加、没有通用写入口（Admin 数据浏览器里只读）。
--
-- 幂等：IF NOT EXISTS，可重复执行。时间戳 TEXT（ISO 字符串，带 +08:00），沿用仓库口径。

ALTER TABLE hygiene_employees ADD COLUMN IF NOT EXISTS "seniority_bonus" BIGINT;

CREATE TABLE IF NOT EXISTS seniority_bonus_changes (
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES tenants(id),
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employee_id" BIGINT NOT NULL,
    "old_value" BIGINT,
    "new_value" BIGINT,
    "changed_by" TEXT NOT NULL,
    "changed_at" TEXT NOT NULL
);

-- 一条访问路径：按人翻他的调整史（新的在后）。没有按时间跨人捞的查询。
CREATE INDEX IF NOT EXISTS idx_seniority_bonus_changes_employee
    ON seniority_bonus_changes (employee_id, changed_at);
